### Wykrywanie phishingowych stron internetowych - Ekstrakcja cech

Notebook stworzony na potrzebę realizacji pracy magisterskiej pod kierunkiem dr hab. Marka Góździa.

## 1. Cel

Strony phishingowe to powszechna metoda inżynierii społecznej, polegająca na podszywaniu się pod zaufane strony internetowe w celu wyłudzenia danych. Celem tego projektu jest zgromadzenie danych i wyodrębnianie wybranego zestawu cech z adresów URL (z ang. Uniform Resource Locator), na bazie których będzie można spróbować sklasyfikować witrynę jako prawdziwą lub phishingową.

### 2. Gromadzenie danych

Aby osiągnąć zadowalający wynik, potrzebujemy wielu adresów URL zarówno tych prawdziwych (oznaczonych w notebooku jako 0) jak i phishignowych (oznaczonych w notebooku jako 1 oraz "podejrzana").

Do zebrania adresów phishingowych wykorzystamy trzy różne serwisy, udostępniające i agregujące tego rodzaju dane.

1. OpenPhish - OpenPhish jest popularnym serwisem, który udostępnia listę zidentyfikowanych stron phishingowych. Miejscem, z którego pobierzemy dane będzie plik https://openphish.com/feed.txt.

2. PhishTank - Ta usługa udostępnia zestaw adresów phishingowych w wielu formatach, takich jak CSV, JSON itp., które są aktualizowane co godzinę. Aby pobrać dane skorzystamy z udostępnionych plików na stronie https://www.phishtank.com/developer_info.php

3. Urlscan.io - Serwis ten pozwala na skanowanie i analizę URLi, w tym wykrywanie stron phishingowych. Oferuje również API, które można wykorzystać do pobierania informacji o prawdziwych, oraz podejrzanych adresach URL. 

W przypadku adresów URL prawdziwych (bezpiecznych) stron, wykorzystamy listę adresów URL oficjalnych stron, należących do znanych firm, które udostępnia serwis urlscan.io (https://urlscan.io/api/v1/pro/availableBrands), oraz listę najpopularniejszych domen, na podstawie liczby odwołujących się do nich podsieci, udostępnianą przez serwis majestic.com (https://pl.majestic.com/reports/majestic-million)

### 2.1 Adresy phishingowe

### OpenPhish

Adresy phishingowe są pobierane z serwisu OpenPhish poprzez odpowiedni endpoint API. Po pobraniu zestawu danych jest on ładowany do ramki DataFrame openphish_data.

In [2]:
import pandas as pd
import requests

In [13]:
import csv

url = 'https://openphish.com/feed.txt'

response = requests.get(url)
# print(response.text)

if response.status_code == 200:
    content = response.content.decode('utf-8')
    
    urls = content.splitlines()
    
    csv_file_name = 'phishing_urls.csv'
    
    with open(csv_file_name, 'w', newline='') as file:
        writer = csv.writer(file)
        
        writer.writerow(['URL'])
        
        for url in urls:
            writer.writerow([url])
    
    print(f'Successfully written to {csv_file_name}')
    
else:
    print('Failed to download the content')

Successfully written to phishing_urls.csv


In [2]:
openphish_data = pd.read_csv('../data/phishing_urls.csv')
openphish_data.head()

URL
0      https://doiw0zuhcw9rosjhic.pages.dev/smart89/
1  https://ipfs.io/ipfs/bafkreiahpgxlkqme2bhj5jfi...
2  https://cloudflare-ipfs.com/ipfs/bafkreiahpgxl...
3  https://start-a-complaint-meta-01061657.pages....
4  https://distritonorte.com.mx/js/config/login.php/

In [3]:
openphish_data.shape

(500, 1)

### PHISHTANK

Adresy phishingowe są pobierane z PhishTanka poprzez odopowiedni endpoint API. Po pobraniu zestawu danych jest on ładowany do ramki DataFrame phishtank_data.

In [8]:
import gzip
import shutil
import os

url = "http://data.phishtank.com/data/online-valid.csv.gz"

downloaded_file = "online-valid.csv.gz"

response = requests.get(url, stream=True)
with open(downloaded_file, 'wb') as file:
    for chunk in response.iter_content(chunk_size=1024):
        if chunk:
            file.write(chunk)

with gzip.open(downloaded_file, 'rb') as f_in:
    with open(downloaded_file[:-3], 'wb') as f_out:  # Usunięcie rozszerzenia .gz
        shutil.copyfileobj(f_in, f_out)

os.remove(downloaded_file)

In [4]:
#loading the phishing URLs data to dataframe
phishtank_data = pd.read_csv("../data/online-valid.csv")
phishtank_data.head()

phish_id                                                url  \
0   8654566  https://us17.list-manage.com/survey?u=95c29488...   
1   8654565           https://newspirit.my/ndanedest/error.php   
2   8654563  https://africantrailphotography.co.za/invsecwm...   
3   8654561      https://btinternetwebmailogin.weeblysite.com/   
4   8654559                       http://2p352yrrr.duckdns.org   

                                    phish_detail_url  \
0  http://www.phishtank.com/phish_detail.php?phis...   
1  http://www.phishtank.com/phish_detail.php?phis...   
2  http://www.phishtank.com/phish_detail.php?phis...   
3  http://www.phishtank.com/phish_detail.php?phis...   
4  http://www.phishtank.com/phish_detail.php?phis...   

             submission_time verified          verification_time online target  
0  2024-07-14T09:28:56+00:00      yes  2024-07-14T09:33:16+00:00    yes  Other  
1  2024-07-14T09:23:59+00:00      yes  2024-07-14T09:33:16+00:00    yes  Other  
2  2024-07-14T09:23:16+00:00      yes  2024-07-14T09:33:16+00:00    yes  Other  
3  2024-07-14T09:22:03+00:00      yes  2024-07-14T09:33:16+00:00    yes  Other  
4  2024-07-14T09:20:30+00:00      yes  2024-07-14T09:33:16+00:00    yes  Other

In [5]:
phishtank_data.shape

(62281, 8)

Pobrany zbiór danych z PhishTanka zawiera 62281 wierszy. W celu zredukowania ilości danych, wybierzemy losowo 4,000 adresów URL. Wybrane adresy zapiszemy ramki DataFrame selected_phishtank.

In [6]:
#Collecting 4,000 Phishing URLs randomly
selected_phishtank = phishtank_data.sample(n = 4000, random_state = 12).copy()
selected_phishtank = selected_phishtank.reset_index(drop=True)
selected_phishtank.head()

phish_id                                                url  \
0   8585872  https://allegrolokalnie.c8a7d9a7.pl/oferta/873...   
1   8625776                         https://www.trx016.asia/a/   
2   8229192  https://cloudflare-ipfs.com/ipfs/bafybeihdtw7y...   
3   8565299  https://docs.google.com/presentation/d/e/2PACX...   
4   8633157                   https://oolx.2384237.xyz/captcha   

                                    phish_detail_url  \
0  http://www.phishtank.com/phish_detail.php?phis...   
1  http://www.phishtank.com/phish_detail.php?phis...   
2  http://www.phishtank.com/phish_detail.php?phis...   
3  http://www.phishtank.com/phish_detail.php?phis...   
4  http://www.phishtank.com/phish_detail.php?phis...   

             submission_time verified          verification_time online  \
0  2024-05-24T08:09:03+00:00      yes  2024-05-28T07:33:34+00:00    yes   
1  2024-06-23T11:19:42+00:00      yes  2024-06-23T12:04:35+00:00    yes   
2  2023-07-19T00:40:39+00:00      yes  2023-07-19T00:43:00+00:00    yes   
3  2024-05-06T18:02:50+00:00      yes  2024-05-06T18:13:04+00:00    yes   
4  2024-06-28T18:40:11+00:00      yes  2024-06-28T18:43:18+00:00    yes   

    target  
0  Allegro  
1    Other  
2    Other  
3    Other  
4    Other

In [7]:
selected_phishtank.shape

(4000, 8)

### URLSCAN

Adresy phishingowe są wczytywane z wygenerowanego pliku urlscanpro-export.csv. Plik ten zawiera informacje o adresach URL sklasyfikowanych jako phishingi. Po pobraniu zestawu danych jest on ładowany do ramki DataFrame urlscan_data.

In [8]:
urlscan_data = pd.read_csv('../data/urlscanpro-export.csv', sep=';')
urlscan_data.head()

Scan Date Scan Method      Scan Source Visibility Submitter  \
0  2024-07-14T11:48:25.694Z         api              NaN   unlisted        us   
1  2024-07-14T11:48:11.973Z   automatic  urlscan-observe   unlisted       NaN   
2  2024-07-14T11:48:10.785Z   automatic  urlscan-observe   unlisted       NaN   
3  2024-07-14T11:46:42.992Z         api              NaN     public        us   
4  2024-07-14T11:46:32.622Z         api              NaN     public        fi   

                                            Scan URL  \
0  https://urlscan.io/result/2cc27262-c12f-46c1-a...   
1  https://urlscan.io/result/7ae49603-bf43-42a5-9...   
2  https://urlscan.io/result/2fd897c3-3940-4144-b...   
3  https://urlscan.io/result/6009a640-5c0e-4d11-8...   
4  https://urlscan.io/result/065e550e-999d-48bd-8...   

                                            Task URL  \
0  https://yeed9.z35.web.core.windows.net/windows...   
1                        https://ausreportinbox.com/   
2                           https://iade-temmuz.sbs/   
3                        https://srz.atazanavir.org/   
4  https://shestripping.com/wp-content/plugins/ar...   

                      Task Domain    Task Apex Domain      Task Tags  ...  \
0  yeed9.z35.web.core.windows.net         windows.net            NaN  ...   
1              ausreportinbox.com  ausreportinbox.com            NaN  ...   
2                 iade-temmuz.sbs     iade-temmuz.sbs            NaN  ...   
3              srz.atazanavir.org      atazanavir.org            NaN  ...   
4                shestripping.com    shestripping.com  @phish_report  ...   

                              Page PTR Record  Page ASN  \
0                                         NaN    AS8075   
1                                         NaN  AS198953   
2                  cpanel16.offshoreracks.com   AS52469   
3                    server.geekwebserver.com  AS393960   
4  ec2-54-235-160-238.compute-1.amazonaws.com   AS14618   

                      Page AS Name  \
0  MICROSOFT-CORP-MSN-AS-BLOCK, US   
1                     PROTON66, RU   
2           Offshore Racks S.A, PA   
3               HOST4GEEKS-LLC, US   
4                   AMAZON-AES, US   

                                   Page Server  \
0  Windows-Azure-Web/1.0 Microsoft-HTTPAPI/2.0   
1                           openresty/1.25.3.1   
2                                       Apache   
3                                       Apache   
4            Apache/2.4.39 (Amazon) PHP/5.6.33   

                                            Page URL  \
0  https://yeed9.z35.web.core.windows.net/windows...   
1                        https://ausreportinbox.com/   
2                           https://iade-temmuz.sbs/   
3                        https://srz.atazanavir.org/   
4  https://shestripping.com/wp-content/plugins/ar...   

                      Page Domain    Page Apex Domain Malicious  \
0  yeed9.z35.web.core.windows.net         windows.net      True   
1              ausreportinbox.com  ausreportinbox.com      True   
2                 iade-temmuz.sbs     iade-temmuz.sbs      True   
3              srz.atazanavir.org      atazanavir.org      True   
4                shestripping.com    shestripping.com      True   

            Brands         Labels  
0  techsupportscam            NaN  
1            govau            NaN  
2             bddk            NaN  
3       salesforce            NaN  
4          nedbank  content.login  

[5 rows x 22 columns]

In [9]:
urlscan_data.shape

(11896, 22)

Zbiór danych z urlscan.io zawiera 11896 wierszy. W celu zredukowania ilości danych, wybierzemy losowo 1,500 adresów URL. Wybrane w ten sposób adresy zapiszemy ramki DataFrame selected_urlscan.

In [10]:
selected_urlscan = urlscan_data.sample(n = 1500, random_state = 12).copy()
selected_urlscan = selected_urlscan.reset_index(drop=True)
selected_urlscan.head()

Scan Date Scan Method Scan Source Visibility Submitter  \
0  2024-07-14T02:23:29.726Z   automatic   openphish     public       NaN   
1  2024-07-14T02:14:18.387Z   automatic   openphish     public       NaN   
2  2024-07-13T23:38:51.389Z         api         NaN   unlisted        us   
3  2024-07-14T08:38:18.570Z         api         NaN     public        us   
4  2024-07-13T23:10:43.898Z         api         NaN     public        us   

                                            Scan URL  \
0  https://urlscan.io/result/f2d0a3d0-df02-4fd9-a...   
1  https://urlscan.io/result/a90a7fec-62a0-492d-a...   
2  https://urlscan.io/result/057096b9-6a17-4510-b...   
3  https://urlscan.io/result/c910185d-427e-4b2b-a...   
4  https://urlscan.io/result/7efebfbe-3c66-46a4-8...   

                                            Task URL  \
0     http://reviews.bussinesaccount.my.id/rever.php   
1              https://amazon-login-nine.vercel.app/   
2  http://ssxcs.com/si6bln/?t=eqav2h0gta/index/us...   
3                        https://qcc.atazanavir.org/   
4  http://pub-8e34ba5d87084c3f9c5d2a23075f50b3.r2...   

                                   Task Domain  \
0                reviews.bussinesaccount.my.id   
1                 amazon-login-nine.vercel.app   
2                                    ssxcs.com   
3                           qcc.atazanavir.org   
4  pub-8e34ba5d87084c3f9c5d2a23075f50b3.r2.dev   

                              Task Apex Domain Task Tags  ...  \
0                        bussinesaccount.my.id       NaN  ...   
1                 amazon-login-nine.vercel.app       NaN  ...   
2                                    ssxcs.com       NaN  ...   
3                               atazanavir.org       NaN  ...   
4  pub-8e34ba5d87084c3f9c5d2a23075f50b3.r2.dev       NaN  ...   

            Page PTR Record  Page ASN                       Page AS Name  \
0                       NaN   AS14061               DIGITALOCEAN-ASN, US   
1                       NaN   AS16509                      AMAZON-02, US   
2                       NaN   AS55933  CLOUDIE-AS-AP Cloudie Limited, HK   
3  server.geekwebserver.com  AS393960                 HOST4GEEKS-LLC, US   
4                       NaN   AS13335                  CLOUDFLARENET, US   

  Page Server                                           Page URL  \
0      Apache    https://reviews.bussinesaccount.my.id/rever.php   
1      Vercel              https://amazon-login-nine.vercel.app/   
2       nginx            https://ssxcs.com/index/user/login.html   
3      Apache                        https://qcc.atazanavir.org/   
4  cloudflare  https://pub-8e34ba5d87084c3f9c5d2a23075f50b3.r...   

                                   Page Domain  \
0                reviews.bussinesaccount.my.id   
1                 amazon-login-nine.vercel.app   
2                                    ssxcs.com   
3                           qcc.atazanavir.org   
4  pub-8e34ba5d87084c3f9c5d2a23075f50b3.r2.dev   

                              Page Apex Domain Malicious        Brands  \
0                        bussinesaccount.my.id      True      facebook   
1                 amazon-login-nine.vercel.app      True        amazon   
2                                    ssxcs.com      True  genericemail   
3                               atazanavir.org      True    salesforce   
4  pub-8e34ba5d87084c3f9c5d2a23075f50b3.r2.dev      True  genericemail   

                                       Labels  
0                                         NaN  
1                                hosting.free  
2                                         NaN  
3                                         NaN  
4  hosting.static,software.cpanel,hosting.cdn  

[5 rows x 22 columns]

In [11]:
selected_urlscan.shape

(1500, 22)

Zebrane adresy phishingowe z tych trzech źródeł złączymy w jedną ramkę danych phishurl, a następnie zapiszemy do pliku phishurl.csv.

In [12]:
# Select only the URL column from each data frame
openphish_urls = openphish_data[['URL']].rename(columns={'URL': 'url'})
selected_phishtank_urls = selected_phishtank[['url']]
selected_urlscan_urls = selected_urlscan[['Page URL']].rename(columns={'Page URL': 'url'})

# Combine all data frames into one
phishurl = pd.concat([openphish_urls, selected_phishtank_urls, selected_urlscan_urls], ignore_index=True)

# Display the first few lines of the resulting data frame
phishurl.head()

url
0      https://doiw0zuhcw9rosjhic.pages.dev/smart89/
1  https://ipfs.io/ipfs/bafkreiahpgxlkqme2bhj5jfi...
2  https://cloudflare-ipfs.com/ipfs/bafkreiahpgxl...
3  https://start-a-complaint-meta-01061657.pages....
4  https://distritonorte.com.mx/js/config/login.php/

Połączone dane phishingowe zawierają 6,000 adresów URL. Dane te nie zawierają dupliaktów.

In [13]:
phishurl.shape

(6000, 1)

Zebrane adresy phishingowe zapiszemy do pliku csv phishurl.csv.

In [14]:
# Storing the phishing URLs data to csv file
phishurl.to_csv('../data/phishurl.csv', index=False)

### 2.2. Prawidłowe (Bezpieczne) adresy URL

### URLSCAN

Adresy bezpiecznych stron z serwisu urlscan.io są wczytywane z wygenerowanego pliku URLSCAN_legit_domains.csv. Po pobraniu zestawu danych jest on ładowany do ramki DataFrame legit_domains.urlscan.

In [5]:
legit_domains_urlscan = pd.read_csv('../data/URLSCAN_legit_domains.csv', names=['url'], header=0)
legit_domains_urlscan.head()

url
0          https://dewatergroep.be
1             https://poppankki.fi
2            https://ceskaposta.cz
3  https://suncoastcreditunion.com
4                   https://caf.fr

Zbiór bezpiecznych adresów URL z urlscan.io zawiera 1288 wierszy.

In [16]:
legit_domains_urlscan.shape

(1288, 1)

### MAJESTIC

Adresy prawdziwych stron z serwisu majestic.com są wczytywane z wygenerowanego pliku majestic_milion.csv. Po pobraniu zestawu danych jest on ładowany do ramki DataFrame. W celu zredukowania ilości danych, wybierzemy pierwsze 4933 wiersze, które następnie zapiszemy do ramki danych legit_domain_majestic.

In [17]:
majestic_milion = pd.read_csv('../data/majestic_million.csv')

legit_domains_majestic = majestic_milion.iloc[:4933]
legit_domains_majestic.head()

GlobalRank  TldRank         Domain  TLD  RefSubNets   RefIPs  \
0           1        1     google.com  com      473803  2145427   
1           2        2   facebook.com  com      465522  2224144   
2           3        3    youtube.com  com      422420  1844676   
3           4        4    twitter.com  com      402407  1715216   
4           5        5  instagram.com  com      367005  1597839   

      IDN_Domain IDN_TLD  PrevGlobalRank  PrevTldRank  PrevRefSubNets  \
0     google.com     com               1            1          472906   
1   facebook.com     com               2            2          464974   
2    youtube.com     com               3            3          421746   
3    twitter.com     com               4            4          401716   
4  instagram.com     com               5            5          366554   

   PrevRefIPs                    Url  
0     2138041     https://google.com  
1     2220575   https://facebook.com  
2     1842025    https://youtube.com  
3     1713711    https://twitter.com  
4     1595937  https://instagram.com

In [18]:
legit_domains_majestic.shape

(4933, 13)

Zebrane adresy prawdziwych stron z serwisów urlscan.io i majestic.com złączymy w jedną ramkę danych legiurl, a następnie zapiszemy do pliku legiurl.csv.

In [19]:
legit_domains_majestic = legit_domains_majestic[['Url']].rename(columns={'Url': 'url'})
legiurl = pd.concat([legit_domains_urlscan, legit_domains_majestic], ignore_index=True)

legiurl.head()

url
0          https://dewatergroep.be
1             https://poppankki.fi
2            https://ceskaposta.cz
3  https://suncoastcreditunion.com
4                   https://caf.fr

In [20]:
legiurl.shape

(6221, 1)

Zebraliśmy 6221 adresów prawdziwych stron internetowych, z czego dane te mogą zawierać duplikaty, ponieważ łączone są z dwóch różnych źródeł. W celu usunięcia duplikatów, wykonujemy operację drop_duplicates. 

In [22]:
legiurl.drop_duplicates(inplace=True)
legiurl.shape

(6000, 1)

W ten sposób uzyskaliśmy 6000 unikalnych adresów URL bezpiecznych stron internetowych. Zapisujemy je do pliku legiurl.csv.

In [131]:
# Storing the legitimate URLs data to csv file
legiurl.to_csv('../data/legiurl.csv', index=False)

### 3. Ekstrakcja cech

Na tym etapie są wyodrębniane poszczególne, wybrane cechy ze zbioru adresów URL oraz stron internetowych, do których prowadzą.

Funkcje w tej sekcji zostały podzielone na trzy kategorie

1. Funkcje oparte na pasku adresu (Adres URL)
2. Funkcje oparte na cechach domeny
3. Funkcje oparte na kodzie HTML i JavaScript stron internetowych

### 3.1. Funkcje oparte na adresie URL:
Z adresu URL można wyodrębnić wiele informacji, które mogą zostać poźniej poddane dalszej analizie. Część z nich może świadczyć o tym, że strona powinna być uznana za podejrzaną. Poniższe metody wyodrębnienia niektórych informacji z adresu URL zostały zaimplementowane w tym projekcie.

1. Domena w adresie URL
2. Adres IP w adresie URL
3. Symbol „@” w adresie URL
4. Długość adresu URL
5. Poziom zagnieżdżenia adresu URL
6. Przekierowanie „//” w adresie URL
7. „http/https” w nazwie domeny
8. Korzystanie z usług skracania adresów URL
9. Prefiks lub sufiks „-” w domenie

Każda z tych funkcji została wyjaśniona i zakodowana poniżej:

In [23]:
from urllib.parse import urlparse
import ipaddress

### 3.1.1. Domena w adresie URL
Tutaj wyodrębniamy domenę obecną w adresie URL. Ta funkcja nie ma większego znaczenia w treningu, dlatego zostanie zignorowana podczas trenowania modelu.

In [24]:
# 1.Domain of the URL (Domain) 
def getDomain(url):
    domain = urlparse(url).netloc
    if re.match(r"^www.", domain):
        domain = domain.replace("www.", "")
    return domain

### 3.1.2. Adres IP w adresie URL
Funkcja sprawdza obecność adresu IP w adresie URL. Adresy URL mogą zawierać adres IP zamiast nazwy domeny, jednak nie jest to typowe dla bezpiecznych stron internetowych. Jeśli zamiast nazwy domeny w adresie URL zostanie użyty adres IP, powinniśmy założyć, że strona jest podejrzana.

Jeśli w adresie URL występuje adres IP, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [25]:
# 2.Checks for IP address in URL (Have_IP)
def havingIP(url):
    try:
        if url.startswith('http://') or url.startswith('https://'):
            url = re.sub(r'https?://', '', url)
        ipaddress.ip_address(url)
        ip = 1
    except:
        ip = 0
    return ip

### 3.1.3. Symbol „@” w adresie URL
Funkcja sprawdza obecność symbolu „@” w adresie URL. Użycie symbolu „@” w adresie URL powoduje, że przeglądarka ignoruje wszystko poprzedzające symbol „@”, a prawdziwy adres często następuje po symbolu „@”.

Jeśli adres URL zawiera symbol „@”, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [26]:
# 3.Checks the presence of @ in URL (Have_At)
def haveAtSign(url):
    if "@" in url:
        at = 1
    else:
        at = 0
    return at

### 3.1.4. Długość adresu URL
Funkcja oblicza długość adresu URL. Oszuści mogą użyć długiego adresu URL, aby ukryć podejrzaną część w pasku adresu. W tym projekcie zakładamy, że jeśli długość adresu URL jest większa lub równa 54 znaków, wówczas adres URL jest klasyfikowany jako phishing, w przeciwnym razie uznajemy adres URL za prawdziwy.

Jeśli długość całego adresu URL >= 54, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [27]:
# 4.Finding the length of URL and categorizing (URL_Length)
def getLength(url):
    if len(url) < 54:
        length = 0
    else:
        length = 1
    return length

### 3.1.5. Poziom zagnieżdżenia adresu URL
Ta funkcja oblicza liczbę podstron w adresie URL na podstawie znaku „/”.

Zwracana wartość funkcji jest liczbą.

In [28]:
# 5.Gives number of '/' in URL (URL_Depth)
def getDepth(url):
    s = urlparse(url).path.split('/')
    depth = 0
    for j in range(len(s)):
        if len(s[j]) != 0:
            depth = depth + 1
    return depth

### 3.1.6. Przekierowanie „//” w adresie URL
Funkcja sprawdza obecność „//” w adresie URL. Obecność znaku „//” w ścieżce adresu URL oznacza, że użytkownik zostanie przekierowany na inną stronę internetową. Jeśli adres URL zaczyna się od „HTTP”, znak „//” powinien pojawić się na szóstej pozycji, jeśli jednak adres URL wykorzystuje protokół „HTTPS”, wówczas „//” powinien pojawić się na siódmej pozycji.

Jeśli znak „//” znajduje się w dowolnym innym miejscu adresu URL poza protokołem, wartość przypisana do tej funkcji wynosi 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [29]:
# 6.Checking for redirection '//' in the url (Redirection)
def redirection(url):
    pos = url.rfind('//')
    if pos > 6:
        if pos > 7:
            return 1
        else:
            return 0
    else:
        return 0

### 3.1.7. „https” w nazwie domeny
Funkcja sprawdza obecność nazwy protokołu „https” w części adresu URL dotyczącej domeny. Oszuści mogą dodać „https” do części adresu URL dotyczącej domeny, aby oszukać użytkowników, że strona jest szyfrowana. Jeśli adres URL zawiera „https” w części domeny, może to być próba oszustwa, ponieważ protokół szyfrowania powinien znajdować się tylko na początku adresu URL, a nie w jego domenie. Taka taktyka może być wykorzystywana przez oszustów do stworzenia fałszywego wrażenia bezpieczeństwa strony. 

Jeśli adres URL zawiera „http/https” w części domeny, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [30]:
# 7.Existence of “HTTPS” in the Domain Part of the URL (https_Domain)
def httpDomain(url):
    domain = urlparse(url).netloc
    if 'https' in domain:
        return 1
    else:
        return 0

### 3.1.8. Korzystanie z usług skracania adresów URL „TinyURL”
Skracanie adresu URL to metoda zmniejszania liczby znaków w linku, w której adres URL może być znacznie krótszy, a mimo to prowadzić do żądanej strony internetowej. Odbywa się to poprzez przekierowanie HTTP w przypadku krótkiej nazwy domeny, która prowadzi do docelowej strony internetowej.

Jeśli adres URL korzysta z popularnych usług skracania, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [31]:
#listing shortening services
shortening_services = r"bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|" \
                      r"yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|" \
                      r"short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|" \
                      r"doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|" \
                      r"qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|q\.gs|is\.gd|" \
                      r"po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|x\.co|" \
                      r"prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|" \
                      r"tr\.im|link\.zip\.net|bl\.ink|rebrandly|clickmeter|cuttly|sniply|hyperlink|dub|zapier|short\.io"

In [32]:
# 8. Checking for Shortening Services in URL (Tiny_URL)
def tinyURL(url):
    match=re.search(shortening_services, url)
    if match:
        return 1
    else:
        return 0

### 3.1.9. Prefiks lub sufiks „-” w domenie
Sprawdzanie obecności „-” w części adresu URL dotyczącej domeny. Symbol myślnika jest rzadko używany w prawidłowych adresach URL. Oszuści często używają przedrostków lub sufiksów oddzielonych (-) w nazwie domeny, aby użytkownicy mieli wrażenie, że mają do czynienia z legalną stroną internetową (np. umcs-edu.pl).

Jeśli adres URL zawiera symbol „-” w części adresu URL dotyczącej domeny, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [33]:
# 9.Checking for Prefix or Suffix Separated by (-) in the Domain (Prefix/Suffix)
def prefixSuffix(url):
    if '-' in urlparse(url).netloc:
        return 1           
    else:
        return 0            

### 3.2. Funkcje oparte na domenie:
Pobieranie poniższych informacji zostało uwzględnione w tym projekcie.

1. Rekord DNS
2. Ruch w witrynie
3. Wiek domeny
4. Czas od utworzenia domeny

Każda z tych funkcji została wyjaśniona i zakodowana poniżej:

In [99]:
!pip install python-whois


[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [34]:
import re
from bs4 import BeautifulSoup
import whois
from datetime import datetime

### 3.2.1. Rekord DNS
W przypadku witryn phishingowych strona często nie jest jeszcze rozpoznawana przez bazę danych WHOIS, albo nie istnieją żadne informacje dotyczące jej nazwy. Jeśli rekord DNS jest pusty lub nie został znaleziony, wartość przypisana do tej funkcji wynosi 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

Ekstrakcja tej informacji została zaimplementowana w funkcji featureExtraction.

In [ ]:
# 11.DNS Record availability (DNS_Record)
# obtained in the featureExtraction function

### 3.2.2. Wiek domeny
Tą informację można wyodrębnić z bazy danych WHOIS. Większość witryn phishingowych działa przez krótki czas. W przypadku tego projektu minimalny okres legalnej domeny założymy jako 12 miesięcy (ponieważ na taki okres zwykle rejestrowane są domeny phishingowe). Wiek jest liczony jako różnica pomiędzy czasem utworzenia i wygaśnięcia.

Jeśli okres domeny < 12 miesięcy, wartość tej funkcji wynosi 1 (strona podejrzana), w przeciwnym razie 0 (strona prawdziwa).

In [35]:
# 13.Survival time of domain: The difference between termination time and creation time (Domain_Age)  
def domainAge(domain_info):
    try:
        creation_date = domain_info.creation_date
        if isinstance(creation_date, list):
            creation_date = creation_date[0]
        if not isinstance(creation_date, datetime):
            try:
                creation_date = datetime.strptime(creation_date, "%Y-%m-%d")
            except TypeError:
                return 1  # Unable to parse date
            except ValueError:
                # Handle cases like "Before 2001"
                if "before" in creation_date.lower():
                    return 1  # Treat as old domain
                else:
                    return 1  # Unable to parse date

        today = datetime.now()
        age = today.year - creation_date.year - ((today.month, today.day) < (creation_date.month, creation_date.day))
        return age
    except AttributeError:
        return 1  # Domain information not available

### 3.2.3. Czas od utworzenia domeny
Funkcja oblicza liczbę dni, która upłynęła od daty rejestracji domeny do chwili obecnej (momentu wykonania programu). Jeśli ten okres jest krótszy niż 3 miesiące (90 dni), funkcja zwraca 1 (strona podejrzana), w przeciwnym razie zwraca 0 (strona prawdziwa).

In [36]:
# 14.End time of domain: The difference between termination time and current time (Domain_End) 
def domainEnd(domain_info):
    if domain_info is None:
        return 1  # Unable to retrieve domain info

    creation_date = domain_info.creation_date

    if creation_date is None:
        return 1  # Missing dates / No information

    # Ensure creation_date is a datetime object
    if isinstance(creation_date, list):
        creation_date = creation_date[0]
    if not isinstance(creation_date, datetime):
        try:
            creation_date = datetime.strptime(creation_date, "%Y-%m-%d")
        except (TypeError, ValueError):
            return 1  # Unable to parse date

    days_since_creation = (datetime.now() - creation_date).days

    return 1 if (days_since_creation < 90) else 0


### 3.3. Funkcje oparte na HTML i JavaScript
Pobranie informacji o poniższych zdarzeniach zostało uwzględnione w tym projekcie.

1. Przekierowanie ramki IFrame
2. Dostosowywanie paska stanu
3. Wyłączanie kliknięcia prawym przyciskiem myszy
4. Przekazywanie strony internetowej

Każda z tych funkcji została wyjaśniona i zakodowana poniżej:

In [37]:
# importing required packages for this section
import requests

### 3.3.1. Przekierowanie ramki IFrame
IFrame to znacznik HTML używany do wyświetlania dodatkowej strony internetowej w aktualnie odwiedzanej witrynie. Oszuści mogą wykorzystać tag „iframe” i uczynić go niewidocznym, tj. pozbawionym obramowań ramki. W tym celu mogą wykorzystać różne atrybuty.

Jeśli ramka iframe jest pusta lub nie zostanie znaleziona odpowiedź, wartość przypisana do tej funkcji to -1, jeśli wykryto podejrzany atrybut 1 (strona podejrzana) lub 0 (strona prawdziwa) w pozostałym przypadku.

In [38]:
# 15. IFrame Redirection (iFrame)
def iframe(response):
    if not response or not hasattr(response, 'text'):
        return -1
    
    soup = BeautifulSoup(response.text, 'html.parser')
    
    iframes = soup.find_all('iframe')
    
    if not iframes:
        return 0
    
    for iframe in iframes:
        if 'style' in iframe.attrs and 'display:none' in iframe['style']:
            return 1
        if 'width' in iframe.attrs and iframe['width'] == '0':
            return 1
        if 'height' in iframe.attrs and iframe['height'] == '0':
            return 1
        if 'frameborder' in iframe.attrs and iframe['frameborder'] == '0':
            return 1
    return 0

### 3.3.2. Dostosowywanie paska stanu
Oszuści mogą używać JavaScriptu do wyświetlania użytkownikom fałszywego adresu URL na pasku stanu. Aby wyodrębnić tę funkcję, musimy wydobyć kod źródłowy strony internetowej, a następnie zdarzenie „onMouseOver” i sprawdzić, czy wprowadza jakieś zmiany na pasku stanu.

Jeśli odpowiedź jest pusta przypisana wartość to -1, jeśli zostanie znaleziona funkcja onmouseover, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [39]:
# 16.Checks the effect of mouse over on status bar (Mouse_Over)
def mouseOver(response):
    if not response or not hasattr(response, 'text'):
        return -1
    
    if re.findall(r'onmouseover', response.text, re.IGNORECASE):
        return 1
    else:
        return 0

### 3.3.3. Wyłączanie kliknięcia prawym przyciskiem myszy
Oszuści wykorzystują JavaScript do wyłączania funkcji kliknięcia prawym przyciskiem myszy, dzięki czemu użytkownicy nie mogą przeglądać i zapisywać kodu źródłowego strony internetowej. Dla tej funkcji będziemy szukać zdarzenia „event.button==2” w kodzie źródłowym strony i sprawdzać, czy użycie prawego przycisku myszy nie zostało wyłączone.

Jeśli odpowiedź jest pusta, zwracana wartość fukcji to -1, jeśli zostanie znalezione polecenie onmouseover, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [40]:
# 17.Checks the status of the right click attribute (Right_Click)
def rightClick(response):
    if not response or not hasattr(response, 'text'):
        return -1
    
    if re.findall(r"event.button ?== ?2", response.text):
        return 1
    else:
        return 0

### 3.3.4. Przekierowanie strony internetowej
Podejrzane strony internetowe często robią kilka przekierowań, zanim użytkownik otrzyma stronę docelową. Złóżmy, że legalne strony internetowe zostały przekierowane maksymalnie dwa razy. Jeśli liczba przekierowań jest większa niż 2, wartość przypisana do tej funkcji to 1 (strona podejrzana) lub 0 (strona prawdziwa) w przeciwnym wypadku.

In [41]:
# 18.Checks the number of forwardings (Web_Forwards)    
def forwarding(response):
    if not response or not hasattr(response, 'history'):
        return -1
    
    if len(response.history) <= 2:
        return 0
    else:
        return 1

### 4. Obliczanie wszystkich funkcji
Poniżej znajduje się zbiorcza metoda, która wywołuje inne funkcje i przechowuje wszystkie pobrane wyniki na liście. Wszystkim przetwarzanym adresom zostanie przypisana etykieta informująca o tym, czy dany adres URL jest phishighiem, czy też nie. Z pomocą tej funkcji wyodrębnimy cechy zarówno stron prawdziwych, jak i phishingowych.

In [42]:
#Function to extract features
def featureExtraction(url, label):
    features = []
    # Address bar based features (9)
    features.append(getDomain(url))
    features.append(havingIP(url))
    features.append(haveAtSign(url))
    features.append(getLength(url))
    features.append(getDepth(url))
    features.append(redirection(url))
    features.append(httpDomain(url))
    features.append(tinyURL(url))
    features.append(prefixSuffix(url))

    # Domain based features (3)
    dns = 0
    try:
        domain_info = whois.whois(urlparse(url).netloc)
    except:
        dns = 1
    
    features.append(dns)
    features.append(1 if dns == 1 else domainAge(domain_info))
    features.append(1 if dns == 1 else domainEnd(domain_info))

    # HTML & Javascript based features (4)
    try:
        response = requests.get(url, timeout=10)
    except:
        response = ""

    features.append(iframe(response))
    features.append(mouseOver(response))
    features.append(rightClick(response))
    features.append(forwarding(response))
    features.append(label)

    return features

### 4.1. Bezpieczne adresy URL:
Teraz wyodrębnianie funkcji wykonamy na adresach URL prawdziwych, bezpiecznych stron internetowych.

In [43]:
legiurl.shape

(6000, 1)

In [44]:
#Extracting the feautres & storing them in a list
legi_features = []
label = 0

for i in range(legiurl.shape[0]):
   try:
       url = legiurl['url'][i]
       legi_features.append(featureExtraction(url,label))
       print(i, url)
   except Exception as e:
       print(f"Error processing URL at index {i}: {e}")
       with open('log.txt', 'a') as f:
           f.write(f"Error processing URL at index {i}: {e}\n")
       continue

0 https://dewatergroep.be
1 https://poppankki.fi
2 https://ceskaposta.cz
3 https://suncoastcreditunion.com
4 https://caf.fr
5 https://teliacompany.com
6 https://ionos.com
7 https://bancaditalia.it
8 https://gazprom.com
9 https://paribu.com
10 https://vectrabank.com
11 https://bsm.sm
12 https://rakbank.ae
13 https://free.fr
14 https://bakerhudsonhealth.com
15 https://ems.com.cn


2024-07-15 09:10:58,786 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


16 https://correo.com.uy
17 https://caisse-epargne.fr
18 https://mps.it
19 https://ac.uk


2024-07-15 09:11:02,717 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


20 https://bpi.com.ph
21 https://kanagawabank.co.jp
22 https://popularenlinea.com
23 https://optimum.net
24 https://bankofireland.com
25 https://redsys.es
26 https://fibank.bg
27 https://mgmresorts.com
28 https://backblaze.com
29 https://mitid.dk


2024-07-15 09:11:43,002 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


30 https://produbanco.com.ec
31 https://bankofcyprus.com
32 https://service.gov.uk
33 https://anpost.com
34 https://ubibanca.com
35 https://bcare.com.sa
36 https://bcbsm.com
37 https://bancodebogota.com
38 https://brandeli.com
39 https://nzpost.co.nz
40 https://gruppocarige.it
41 https://metlife.com
42 https://post.gov.tw
43 https://konami.com
44 https://openbank.es
45 https://kpn.nl
46 https://libero.it
47 https://infinitepay.io
48 https://inail.it
49 https://bni.co.id
50 https://crypto.com
51 https://mizuhogroup.com
52 https://who.int
53 https://oberbank.com
54 https://cypruspost.post
55 https://interac.ca
56 https://hbl.com
57 https://ally.com
58 https://bankofamerica.com
59 https://salesforce.com
60 https://onet.pl
61 https://broadviewfcu.com
62 https://bankofoklahoma.com
63 https://interactivebrokers.ie
64 https://visa.com
65 https://sofinco.fr
66 https://pichincha.com
67 https://asurion.com
68 https://yak.ca
69 https://firstontario.com
70 https://mailgun.com
71 https://belgium.be

2024-07-15 09:14:20,366 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


88 https://vietcombank.com.vn
89 https://microsoft.de
90 https://iccu.com
91 https://hype.it
92 https://supervielle.com.ar
93 https://ncbank.co.jp
94 https://altibox.no
95 https://sab.com
96 https://laposte.fr
97 https://taishinbank.com.tw
98 https://crelan.be
99 https://caixa.gov.br
100 https://twitter.com
101 https://pennymac.com
102 https://southstatebank.com
103 https://bankid.no
104 https://ee.co.uk
105 https://beobank.be
106 https://aa.com
107 https://dbs.com
108 https://posti.fi
109 https://ecu.com
110 https://knab.nl
111 https://runescape.com
112 https://bancacambiano.it
113 https://infocert.it
114 https://pzu.pl
115 https://netsons.com
116 https://craigslist.org
117 https://simply.com
118 https://giffgaff.com
119 https://hipercard.com.br
120 https://b-cas.co.jp
121 https://essent.nl
122 https://dfj.com
123 https://hse.ie
124 https://apobank.de
125 https://microsoft.com
126 https://family.co.jp
127 https://recurly.com
128 https://gmo-aozora.com
129 https://match.com
130 https:/

2024-07-15 09:17:57,815 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


175 https://mbway.pt
176 https://hellenicbank.com
177 https://ficohsa.com
178 https://myetherwallet.com


2024-07-15 09:18:17,705 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


179 https://bgr.com.ec
180 https://centurylink.com
181 https://nykredit.dk
182 https://nextdoor.com
183 https://webex.com
184 https://jncb.com
185 https://sella.it
186 https://bcr.ro
187 https://earthlink.net
188 https://mercuryinsurance.com
189 https://applefcu.org
190 https://smbc.co.jp
191 https://umass.edu
192 https://cib.hu
193 https://riyadbank.com
194 https://lg.jp
195 https://kvk.nl
196 https://mobit.ne.jp
197 https://uber.com
198 https://ulsterbank.ie
199 https://leagueoflegends.com
200 https://comcast.com
201 https://three.co.uk
202 https://kiwibank.co.nz
203 https://paypal.com
204 https://intuit.com
205 https://viewsnet.jp
206 https://manulife.ca
207 https://filetransfer.io
208 https://squareup.com
209 https://networksolutions.com
210 https://vipps.no
211 https://airbnb.ae
212 https://rbs.co.uk
213 https://skatteetaten.no
214 https://jyskebank.dk
215 https://gov.hu
216 https://telstra.com.au


2024-07-15 09:19:49,108 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


217 https://gtc.com.gt
218 https://energyaustralia.com.au
219 https://lufthansa.com
220 https://github.com
221 https://mastercard.us
222 https://naver.com


2024-07-15 09:20:14,500 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


223 https://milleniumbcp.pt
224 https://telefonica.com
225 https://tiaa.org
226 https://spark.co.nz
227 https://dpd.com
228 https://costco.com


2024-07-15 09:20:31,022 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


229 https://abbank.vn
230 https://cbonline.co.uk
231 https://itau.cl
232 https://spotify.com
233 https://btcturk.com
234 https://cogeco.ca


2024-07-15 09:20:51,682 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


235 https://bienlinea.bi.com.gt
236 https://paxful.com
237 https://coopenae.fi.cr
238 https://gov.tr
239 https://maaden.com.sa
240 https://mooney.it
241 https://gov
242 https://allegro.pl
243 https://sydbank.dk
244 https://softbank.jp
245 https://edfenergy.com
246 https://usbank.com
247 https://canadapost.ca
248 https://sara.it
249 https://realizesolucoesfinanceiras.com.br
250 https://bankofguam.com
251 https://bahrain.bh
252 https://true.th
253 https://get-carrot.com
254 https://zurich.com
255 https://hdb.gov.sg
256 https://dandomain.dk
257 https://bpn.com.ar
258 https://bancamiga.com
259 https://poste.it
260 https://saastopankki.fi
261 https://bestchange.com
262 https://markel.com
263 https://nestle.com
264 https://belfius.be
265 https://axia.com
266 https://bahrainpost.gov.bh
267 https://endesa.com
268 https://bankofscotland.co.uk
269 https://bunq.com
270 https://modulbank.ru
271 https://thisdoesnotexist.com
272 https://tetrapak.com
273 https://square-enix.com
274 https://zipwhip.co

2024-07-15 09:26:23,499 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


321 https://brou.com.uy
322 https://youngplatform.com
323 https://gob.mx
324 https://ahliunited.com
325 https://postnl.nl
326 https://cox.com
327 https://pelicanstatecu.com
328 https://bot.com.tw
329 https://aliant.bell.ca
330 https://distributel.ca
331 https://popolarebari.it
332 https://grupobancolombia.com
333 https://veridiancu.org
334 https://gemini.com
335 https://hands.net
336 https://bancoazteca.com.mx
337 https://nvidia.com
338 https://binance.com
339 https://zain.com
340 https://ibex.co
341 https://kfc.com
342 https://vakifbank.com.tr
343 https://fassil.com.bo
344 https://podium.com
345 https://bankmillenium.pl
346 https://becu.org
347 https://lacassa.com
348 https://one.nz
349 https://ana.co.jp
350 https://cctv.com
351 https://e-zpassny.com
352 https://sygeforsikring.dk


2024-07-15 09:27:43,254 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


353 https://bantrab.com.gt
354 https://bpp.it
355 https://bosbank.pl
356 https://payid.com.au
357 https://emiratesnbd.com
358 https://handelsbanken.se
359 https://lazard.com
360 https://boq.com.au
361 https://co-operativebank.co.uk
362 https://bgk.pl
363 https://virgin.com
364 https://alexbank.com
365 https://sb.lt
366 https://godaddy.com
367 https://pfizer
368 https://latam.com
369 https://mbhbank.hu
370 https://rcu.org
371 https://gov.au
372 https://ripsa.com.ar
373 https://wetransfer.com
374 https://northlane.com
375 https://shinseifinancial.co.jp
376 https://mercedes-benz.com
377 https://windtre.it
378 https://ing.de
379 https://velocity.black
380 https://cajamar.es
381 https://starhub.com
382 https://newyorklife.com
383 https://vr.de
384 https://serverplan.com
385 https://stripe.com
386 https://alaskausa.org
387 https://gucci.com
388 https://lululemon.com
389 https://szkb.ch
390 https://jabank.org
391 https://balenciaga.com
392 https://benefit.bh
393 https://lumine.jp
394 https://

2024-07-15 09:30:18,001 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


407 https://eurobank.gr
408 https://oitabank.co.jp
409 https://mail.ru
410 https://velobank.pl
411 https://northerntel.ca
412 https://aeon.co.jp
413 https://adcb.com


2024-07-15 09:30:50,125 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


414 https://gov.pt
415 https://zkb.ch
416 https://grab.com
417 https://hanover.com
418 https://siemens.com
419 https://starlink.com
420 https://macro.com.ar
421 https://crvolterra.it
422 https://incomm.com
423 https://mifel.net
424 https://payoneer.com
425 https://shell.com
426 https://disney.com
427 https://francfranc.com
428 https://ziggo.nl
429 https://walmart.com
430 https://mimecast.com
431 https://cherrybank.it
432 https://capitalone.com
433 https://obos.no
434 https://valitor.is
435 https://ts3card.com
436 https://europa.eu
437 https://bancavalsabbina.com
438 https://ups.com
439 https://bancodelapampa.com.ar
440 https://alinma.com
441 https://fnbank.net
442 https://bci.cl
443 https://chebanca.it
444 https://fnac.com
445 https://uol.com.br
446 https://credit-du-nord.fr
447 https://metrobankonline.co.uk
448 https://ea.com
449 https://wallapop.com
450 https://jcom.co.jp
451 https://serasa.com.br
452 https://banpais.hn
453 https://nsbank.com
454 https://mailjet.com
455 https://banki

2024-07-15 09:34:04,462 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


488 https://banesco.com.pa
489 https://bancosantafe.com.ar
490 https://nbc.ca
491 https://paidy.com
492 https://tokero.com
493 https://secumd.org
494 https://przelewy24.pl
495 https://sgx.com
496 https://dkb.de
497 https://wizink.es
498 https://homedepot.com
499 https://kredinor.no
500 https://daum.net
501 https://halkbank.com.tr
502 https://bn.com.pe
503 https://snsbank.nl
504 https://tnt.fr
505 https://vodafone.com
506 https://sentosa.com.sg
507 https://maybank2u.com.my
508 https://maersk.com
509 https://hirogin.co.jp
510 https://bnpparibas.de
511 https://auspost.com.au
512 https://hubspot.com
513 https://interbank.pe
514 https://chronopost.fr
515 https://citizensbank.com
516 https://nab.com.au
517 https://telenor.no
518 https://allegrolokalnie.pl
519 https://desertfinancial.com
520 https://constantcontact.com
521 https://livelo.com.br
522 https://pbebank.com
523 https://instagram.com
524 https://posta.sk
525 https://gmx.de
526 https://orlen.pl
527 https://shinseibank.com
528 https:/

2024-07-15 09:37:33,732 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


576 https://piraeusbank.gr
577 https://boursorama.com
578 https://xfinity.com
579 https://tangerine.ca
580 https://timberlandbank.com
581 https://pleo.io
582 https://irakyat.com.my
583 https://2dehands.be
584 https://vgz.nl
585 https://squarespace.com
586 https://sfr.fr
587 https://eika.no
588 https://bank99.at
589 https://svb.com
590 https://championcu.com
591 https://bancodelpacifico.com
592 https://crocs.de
593 https://chibabank.co.jp
594 https://netflix.com
595 https://shizuokabank.co.jp
596 https://loft.co.jp
597 https://mmc.com
598 https://strato.de
599 https://otpbank.hu
600 https://bancoripley.com.pe
601 https://bancointer.com.br
602 https://blubanca.it
603 https://nationwide.co.uk
604 https://cinfin.com
605 https://telus.com
606 https://credifoz.coop.br
607 https://dmm.com
608 https://sbm.no
609 https://halifax.co.uk
610 https://wellsfargo.com
611 https://labanquepostale.fr
612 https://mobilepay.dk
613 https://one.com
614 https://shimachu.co.jp
615 https://spf.gov.sg
616 https

2024-07-15 09:40:57,895 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


656 https://gov.gr
657 https://hetzner.de
658 https://saksfifthavenue.com
659 https://xero.com
660 https://stretto.com
661 https://line.me
662 https://americafirst.com
663 https://rackspace.com
664 https://nkmenergia.hu
665 https://alibaba.com
666 https://td.com
667 https://deutsche-bank.de
668 https://unipd.it
669 https://apple.com
670 https://six-group.com
671 https://arionbanki.is
672 https://irs.gov
673 https://juno.com
674 https://mercadopago.com.ar
675 https://retik.com


2024-07-15 09:41:51,391 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10054] An existing connection was forcibly closed by the remote host


676 https://jurokubank.chance.co.jp
677 https://block.xyz
678 https://huntington.com
679 https://zendesk.com
680 https://oreilly.com
681 https://unum.com
682 https://jep.coop
683 https://eposcard.co.jp
684 https://fibabanka.com.tr
685 https://commerzbank.com
686 https://surugabank.co.jp
687 https://klaviyo.com
688 https://tsb.co.uk
689 https://posta-romana.ro
690 https://discordapp.com
691 https://hongkongpost.hk
692 https://box.com
693 https://communityamerica.com
694 https://mobile.de
695 https://slack.com
696 https://onlyfans.com
697 https://bcp.it
698 https://spv.no
699 https://optus.com.au
700 https://vystarcu.org
701 https://nobullproject.com
702 https://sf-express.com
703 https://biverbanca.it
704 https://boc.cn
705 https://vmi.lt
706 https://canvas.ne.jp
707 https://bancsabadell.com
708 https://tide.co
709 https://dnb.no
710 https://citi.com
711 https://wvfcu.org
712 https://bitbank.cc
713 https://europages.com
714 https://immowelt.de
715 https://unige.ch
716 https://activecamp

2024-07-15 09:47:44,225 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


795 https://bdo.com.ph
796 https://dhs.gov
797 https://gob.pe
798 https://landbank.com
799 https://jio.com
800 https://luminor.lt
801 https://zozo.jp
802 https://sony.com
803 https://gov.pl
804 https://bancofalabella.com.co
805 https://silvergate.com
806 https://triodos.de
807 https://singpass.gov.sg
808 https://alandsbanken.fi
809 https://leboncoin.fr
810 https://paxos.com
811 https://foundever.com
812 https://bancaifis.it
813 https://huawei.com
814 https://cutx.org
815 https://frontier.com
816 https://aktia.fi
817 https://erstebank.hu
818 https://onpointcu.com
819 https://capitecbank.co.za
820 https://iblbanca.it
821 https://walkme.com
822 https://iledefrance-mobilites.fr
823 https://bendigobank.com.au
824 https://bet365.com
825 https://onlinesbi.com
826 https://heylogin.com
827 https://nfp.com
828 https://reyl.com
829 https://etrade.com
830 https://ica.gov.sg
831 https://willbank.com.br
832 https://arcteryx.com
833 https://amicahr.co.uk
834 https://credit-agricole.fr
835 https://ban

2024-07-15 09:52:38,202 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


901 https://elta.gr
902 https://hydroquebec.com
903 https://dotpay.pl
904 https://posta.si
905 https://att.com
906 https://capitalgroup.com
907 https://motusbank.ca
908 https://dcu.ie
909 https://doordash.com
910 https://popso.it
911 https://asahi-life.co.jp
912 https://tbcbank.ge
913 https://hokuyobank.co.jp
914 https://embers.org
915 https://zoho.eu
916 https://orangebank.fr
917 https://oney.com
918 https://taskus.com
919 https://consorsbank.de
920 https://blockchain.com
921 https://mweb.co.za
922 https://posten.no
923 https://expressvpn.com
924 https://gov.cz
925 https://elster.de
926 https://bddk.org.tr
927 https://civibank.it
928 https://post.at
929 https://sbb.ch
930 https://kraken.com
931 https://amocofcu.org
932 https://dfcufinancial.com
933 https://bnz.co.nz
934 https://chainlinklabs.com


2024-07-15 09:54:20,071 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


935 https://alpha.gr
936 https://suomi.fi
937 https://unitedfcu.com
938 https://nordstrom.com
939 https://kbc.ie
940 https://storebrand.no
941 https://windstream.com
942 https://esunbank.com.tw
943 https://ziprecruiter.com
944 https://register.it
945 https://suntrust.com
946 https://migros.ch
947 https://boxberry.ru
948 https://stcu.org
949 https://gcash.com
950 https://sadad.com
951 https://davivienda.com
952 https://bancor.com.ar
953 https://scb.co.th
954 https://mtb.com
955 https://temu.com
956 https://qatarpost.qa
957 https://postnord.se
958 https://postbank.bg
959 https://codashop.com
960 https://tsys.com
961 https://jaccs.co.jp
962 https://okta.com
963 https://targobank.de
964 https://qnbfinansbank.com
965 https://www.aresmgmt.com
966 https://midjourney.com
967 https://inbank.it
968 https://mascomabank.com
969 https://cnba.com
970 https://ledger.com
971 https://nordea.com
972 https://bancaetica.it
973 https://mom.gov.sg
974 https://ualberta.ca
975 https://bhd.com.do
976 https://p

2024-07-15 09:57:16,776 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1012 https://familiar.com.py
1013 https://telesign.com
1014 https://agriaffaires.fr
1015 https://pvbank.com
1016 https://shopify.com
1017 https://mirror.co.uk
1018 https://gov.sa
1019 https://bcu.org
1020 https://avatrade.com
1021 https://mufg.jp
1022 https://sunrise.ch
1023 https://docusign.com
1024 https://uob.com.sg
1025 https://lafise.com
1026 https://accessbankplc.com
1027 https://fidor.de
1028 https://olxgroup.com
1029 https://uiowa.edu


2024-07-15 09:58:03,227 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1030 https://pnb.com.ph
1031 https://qualcomm.com
1032 https://viseca.ch
1033 https://rakuten.com


2024-07-15 09:58:22,168 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


1034 https://bancobpi.pt
1035 https://qoo10.jp
1036 https://landsbankinn.is
1037 https://teachersfcu.org
1038 https://keytradebank.be
1039 https://agoda.com
1040 https://webank.it
1041 https://hbl.ch
1042 https://unitedhealthgroup.com
1043 https://cmb.fr
1044 https://vinted.de
1045 https://creditmutuel.fr
1046 https://lottomatica.it
1047 https://firstdirect.com
1048 https://rbfcu.org
1049 https://wise.com
1050 https://ffbkc.com
1051 https://macquarie.com.au
1052 https://nta.go.jp
1053 https://amegybank.com


2024-07-15 09:59:08,258 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1054 https://nbg.gr
1055 https://firstrepublic.com
1056 https://zionsbank.com
1057 https://dskbank.bg
1058 https://bancobpm.it
1059 https://autopay.io
1060 https://homeaway.com
1061 https://steampowered.com
1062 https://alahli.com
1063 https://fiverr.com
1064 https://ourtime.com
1065 https://uccard.co.jp
1066 https://georgiasown.org
1067 https://payu.com
1068 https://mbank.pl
1069 https://fedex.com
1070 https://mcdonalds.com
1071 https://travel.gc.ca
1072 https://united.com
1073 https://hsbc.com
1074 https://evernote.com


2024-07-15 10:00:02,732 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1075 https://gov.ph
1076 https://santanderbank.com
1077 https://atb.com
1078 https://pekao.com.pl
1079 https://lastpass.com


2024-07-15 10:00:11,444 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1080 https://metrobank.com.ph
1081 https://pkobp.pl
1082 https://patagonia.com
1083 https://bancobcr.com
1084 https://pub.gov.sg
1085 https://akb.ch
1086 https://telkomsel.com
1087 https://myhermes.co.uk
1088 https://tripadvisor.com
1089 https://zellepay.com
1090 https://luno.com
1091 https://chase.com
1092 https://bmo.com
1093 https://swisscom.ch
1094 https://americanas.com.br
1095 https://etisalat.ae
1096 https://mailchimp.com
1097 https://smartsheet.com
1098 https://subito.it
1099 https://ebox.ca
1100 https://natwest.com
1101 https://casasbahia.com.br
1102 https://macu.com
1103 https://cloudflare.com
1104 https://kagin.co.jp
1105 https://eni.com
1106 https://sevenbank.co.jp
1107 https://post.ch
1108 https://visionsfcu.org


2024-07-15 10:01:17,150 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1109 https://banprogrupopromerica.com.ni
1110 https://posturinn.is
1111 https://dofus.com
1112 https://unionbank.com
1113 https://sbanken.no
1114 https://ubank.com.au
1115 https://hiworks.com
1116 https://nestbank.pl
1117 https://bancadiasti.it
1118 https://hdfcbank.com
1119 https://israelpost.co.il
1120 https://caixabank.es
1121 https://etc-meisai.jp
1122 https://papara.com
1123 https://bitfinex.com
1124 https://workday.com
1125 https://uhaul.com
1126 https://jcb.co.jp
1127 https://mitsui-shopping-park.com
1128 https://id.me
1129 https://allianz.de
1130 https://18shinwabank.co.jp
1131 https://uniswap.org
1132 https://singpost.com
1133 https://kayak.com
1134 https://asnbank.nl
1135 https://ent.com
1136 https://outlook.live.com
1137 https://orange.fr


2024-07-15 10:02:12,059 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1138 https://bancopromerica.com.gt
1139 https://vk.com
1140 https://mercari.com
1141 https://407etr.com
1142 https://enel.com
1143 https://inkasso.is
1144 https://gtbank.com
1145 https://greenstate.org
1146 https://unipin.com
1147 https://snapchat.com
1148 https://authy.com
1149 https://roblox.com
1150 https://bancasantangelo.com
1151 https://robinhood.com
1152 https://redfcu.org
1153 https://argos.co.uk
1154 https://hoka.com
1155 https://klp.no
1156 https://rbcroyalbank.com
1157 https://correios.com.br
1158 https://bancadiimola.it
1159 https://carifermo.it
1160 https://bankmellat.ir
1161 https://danskebank.com
1162 https://orsted.com
1163 https://advanzia.com
1164 https://web.de
1165 https://tescobank.com
1166 https://bankofthewest.com
1167 https://mypos.com
1168 https://1password.com
1169 https://busey.com
1170 https://garanti.com.tr
1171 https://findomestic.it
1172 https://lloydsbank.com
1173 https://posb.com.sg
1174 https://heroku.com
1175 https://gulfair.com
1176 https://bancodesi

2024-07-15 10:03:52,904 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1178 https://banrural.com.gt
1179 https://vinci-autoroutes.com
1180 https://viacredi.coop.br
1181 https://bancopatagonia.com.ar
1182 https://lmax.com
1183 https://telekom.de
1184 https://regiobank.nl


2024-07-15 10:04:24,229 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1185 https://globalbank.com.pa
1186 https://homegate.ch
1187 https://anz.com.au
1188 https://lifecard.co.jp
1189 https://clicksend.com
1190 https://ibercaja.es
1191 https://seb.lt
1192 https://nickel.eu
1193 https://bancociudad.com.ar
1194 https://nbbonline.com
1195 https://resonabank.co.jp
1196 https://scotiabank.com
1197 https://hulu.com
1198 https://uphold.com
1199 https://ubs.com
1200 https://britishgas.co.uk
1201 https://53.com
1202 https://localbitcoins.com
1203 https://bangkokbank.com
1204 https://gouv.fr
1205 https://lawsonbank.jp
1206 https://vub.sk
1207 https://neteller.com
1208 https://sky.com
1209 https://bittrex.com
1210 https://sparebank1.no
1211 https://westpac.com.au
1212 https://fgov.be
1213 https://cmegroup.com


2024-07-15 10:06:17,110 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


1214 https://cgd.pt
1215 https://nitori-net.jp
1216 https://brandshield.com
1217 https://tim.it
1218 https://ethereum.org
1219 https://royalmail.com
1220 https://statestreet.com
1221 https://bancapassadore.it
1222 https://supercell.com
1223 https://eon.de
1224 https://csgoempire.com
1225 https://tymebank.co.za
1226 https://dropbox.com
1227 https://vancity.com
1228 https://firstcitizens.com
1229 https://venmo.com
1230 https://correosexpress.com
1231 https://lta.gov.sg
1232 https://lbb.de
1233 https://eurocard.com
1234 https://moongate.id
1235 https://deltacommunitycu.com
1236 https://avvillas.com.co
1237 https://blackrock.com
1238 https://kfw.de
1239 https://bper.it
1240 https://bancochile.cl
1241 https://usps.com
1242 https://avito.ru
1243 https://bbt.com
1244 https://voi.0101.co.jp
1245 https://ripio.com
1246 https://acerta.be
1247 https://aboutamazon.eu
1248 https://japannetbank.co.jp
1249 https://go.jp
1250 https://luckymobile.ca
1251 https://smtb.jp
1252 https://bplazio.it


2024-07-15 10:08:14,983 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


1253 https://novobanco.pt


2024-07-15 10:08:25,866 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


1254 https://ctt.pt
1255 https://jal.co.jp
1256 https://bancoagricola.com
1257 https://pochta.ru
1258 https://frostbank.com
1259 https://bestbuy.com
1260 https://unicredit.it
1261 https://floabank.fr
1262 https://gls-group.com
1263 https://jibunbank.co.jp
1264 https://brt.it
1265 https://arvest.com
1266 https://batelco.com
1267 https://bancamediolanum.it
1268 https://isybank.com
1269 https://key.com
1270 https://peoples.com
1271 https://autoscout24.de
1272 https://sunlife.com
1273 https://pgbank.com
1274 https://aramco.com
1275 https://butterfield.com
1276 https://marriott.com
1277 https://circle.com
1278 https://island.is
1279 https://gm.com
1280 https://ubp.com
1281 https://gov.lv
1282 https://boy.co.jp
1283 https://emirates.com
1284 https://poczta-polska.pl
1285 https://epicgames.com
1286 https://movistar.es
1287 https://eki-net.com
Error processing URL at index 1288: 1288
Error processing URL at index 1289: 1289
1290 https://youtube.com
Error processing URL at index 1291: 1291
Erro

2024-07-15 10:13:47,067 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


1428 https://amzn.to
1429 https://beian.gov.cn
1430 https://go.com
1431 https://npr.org
1432 https://wired.com
1433 https://dailymail.co.uk
1434 https://usatoday.com
1435 https://telegraph.co.uk
1436 https://googleusercontent.com
1437 https://addtoany.com
1438 https://ted.com
1439 https://telegram.me
1440 https://commons.wikimedia.org
1441 https://hp.com
1442 https://cnet.com
1443 https://surveymonkey.com
1444 https://myshopify.com
1445 https://launchpad.net
1446 https://ebay.com
1447 https://aboutads.info
1448 https://debian.org
1449 https://mysql.com
1450 https://twitch.tv
1451 https://etsy.com
1452 https://loc.gov
1453 https://gc.ca
1454 https://wix.com
1455 https://i0.wp.com
1456 https://blogger.com
1457 https://oup.com
1458 https://behance.net
1459 https://validator.w3.org
1460 https://independent.co.uk
1461 https://berkeley.edu
Error processing URL at index 1462: 1462
1463 https://ietf.org
1464 https://discord.gg
1465 https://techcrunch.com
1466 https://ft.com
Error processing UR

2024-07-15 10:15:28,027 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1511 https://mailchi.mp
Error processing URL at index 1512: 1512
1513 https://theatlantic.com
1514 https://pixabay.com
1515 https://jotform.com
1516 https://princeton.edu
1517 https://investopedia.com
1518 https://bandcamp.com
1519 https://iso.org
Error processing URL at index 1520: 1520
1521 https://groups.google.com
1522 https://cambridge.org
1523 https://nbcnews.com
1524 https://whitehouse.gov
1525 https://youku.com
1526 https://dx.doi.org
1527 https://hugedomains.com
1528 https://epa.gov
Error processing URL at index 1529: 1529
1530 https://de.wikipedia.org
1531 https://usda.gov
1532 https://business.site
1533 https://plesk.com
1534 https://taobao.com
1535 https://example.com
Error processing URL at index 1536: 1536
1537 https://kickstarter.com
Error processing URL at index 1538: 1538
1539 https://quora.com
Error processing URL at index 1540: 1540
1541 https://worldbank.org
1542 https://healthline.com
1543 https://mayoclinic.org
1544 https://finance.yahoo.com
1545 https://scribd.co

2024-07-15 10:23:19,355 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1766 https://telegra.ph
1767 https://www.nhs.uk
1768 https://nyu.edu
1769 https://w3schools.com
1770 https://teamviewer.com
1771 https://google.ca
1772 https://jd.com
1773 https://qc.ca
Error processing URL at index 1774: 1774
1775 https://withgoogle.com
1776 https://m.me
1777 https://getpocket.com
1778 https://feeds.feedburner.com
1779 https://zhihu.com
1780 https://livescience.com
1781 https://ssrn.com
1782 https://wikia.com
1783 https://bbb.org
1784 https://sitemaps.org
1785 https://i.imgur.com
1786 https://sec.gov
1787 https://qz.com
1788 https://anchor.fm
1789 https://moodle.org
1790 https://shutterstock.com
1791 https://aljazeera.com
1792 https://chicagotribune.com
1793 https://acm.org
1794 https://kernel.org
1795 https://howstuffworks.com
1796 https://bizjournals.com
1797 https://office365.com
1798 https://netscape.com
Error processing URL at index 1799: 1799
1800 https://mitre.org
1801 https://purdue.edu
1802 https://trello.com
Error processing URL at index 1803: 1803
1804 http

2024-07-15 10:32:30,451 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


2020 https://army.mil
2021 https://cpan.org
2022 https://ethz.ch
Error processing URL at index 2023: 2023
2024 https://semrush.com
2025 https://greenpeace.org
2026 https://1688.com
2027 https://nasdaq.com
2028 https://netlify.app
2029 https://heylink.me
2030 https://youronlinechoices.eu
2031 https://globo.com
2032 https://tamu.edu
2033 https://nsw.gov.au
2034 https://fool.com
2035 https://urldefense.com
2036 https://paypal.me
2037 https://spb.ru
2038 https://usa.gov
2039 https://amazon.ca
2040 https://thebalancemoney.com
2041 https://fliphtml5.com
2042 https://ohchr.org
2043 https://ovhcloud.com
2044 https://amazon.fr
2045 https://gmail.com
2046 https://curl.se
2047 https://bitbucket.org
2048 https://autodesk.com
2049 https://amd.com
2050 https://imagemagick.org
2051 https://crunchbase.com
2052 https://wa.link
2053 https://ipcc.ch
2054 https://novell.com
2055 https://cbslocal.com
2056 https://salon.com
2057 https://haxx.se
2058 https://nodejs.org
2059 https://eventbrite.co.uk
2060 http

2024-07-15 10:36:58,383 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


2109 https://navy.mil
2110 https://vogue.com
2111 https://ncsu.edu
2112 https://verywellmind.com
2113 https://lonelyplanet.com
2114 https://nyc.gov
2115 https://fifa.com
2116 https://calameo.com
2117 https://google.com.au
2118 https://outlookindia.com
2119 https://vanityfair.com
2120 https://over-blog.com
Error processing URL at index 2121: 2121
2122 https://ndtv.com
2123 https://ucsb.edu
2124 https://digitalocean.com
2125 https://texas.gov
Error processing URL at index 2126: 2126
2127 https://broadcom.com
2128 https://hrw.org
2129 https://icann.org
2130 https://aarp.org
2131 https://lin.ee
Error processing URL at index 2132: 2132
2133 https://shorturl.at
2134 https://last.fm
2135 https://speedtest.net
2136 https://mpg.de
2137 https://indiana.edu
2138 https://tableau.com
2139 https://themegrill.com
2140 https://xbox.com
2141 https://georgetown.edu
2142 https://gamespot.com
2143 https://lego.com
2144 https://iheart.com
2145 https://miibeian.gov.cn
2146 https://prweb.com
2147 https://wp.

2024-07-15 10:41:26,329 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


2228 https://vatican.va
2229 https://yumpu.com
2230 https://sketchfab.com
Error processing URL at index 2231: 2231
2232 https://jpost.com
2233 https://snopes.com
2234 https://deadline.com
2235 https://or.id
2236 https://prestashop.com
2237 https://service.weibo.com
2238 https://isc.org
2239 https://findlaw.com
Error processing URL at index 2240: 2240
2241 https://iea.org
2242 https://sfu.ca
2243 https://nic.in
2244 https://perl.com
2245 https://smugmug.com
2246 https://heise.de
2247 https://weather.gov
2248 https://cosmopolitan.com
2249 https://timeout.com
2250 https://oxfordjournals.org
2251 https://clinicaltrials.gov
2252 https://foodnetwork.com
2253 https://brown.edu
Error processing URL at index 2254: 2254
2255 https://herokuapp.com
2256 https://fontawesome.com
2257 https://mcgill.ca
2258 https://mercurynews.com
2259 https://wikisource.org
2260 https://phpbb.com
2261 https://lse.ac.uk
2262 https://ampproject.org
2263 https://ctvnews.ca
2264 https://accuweather.com
2265 https://bell

2024-07-15 10:43:37,449 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


2279 https://yp.to
2280 https://gatech.edu
2281 https://es.wordpress.org
2282 https://defense.gov
2283 https://blogs.wsj.com
Error processing URL at index 2284: 2284
2285 https://ssa.gov
2286 https://repubblica.it
2287 https://indianexpress.com
2288 https://goodhousekeeping.com
2289 https://lg.com
2290 https://fema.gov
Error processing URL at index 2291: 2291
2292 https://toutiao.com
2293 https://hindawi.com
2294 https://google.com.br
2295 https://federalregister.gov
2296 https://redbull.com
2297 https://msnbc.com
2298 https://mega.nz
2299 https://qcloud.com
2300 https://japantimes.co.jp
2301 https://videolan.org
2302 https://matomo.org
2303 https://answers.com
2304 https://foxbusiness.com
2305 https://washingtontimes.com
2306 https://yandex.com
2307 https://unhcr.org
2308 https://mediawiki.org
2309 https://rsc.org
2310 https://patch.com
2311 https://asso.fr
2312 https://searchengineland.com
2313 https://360.cn
2314 https://sueddeutsche.de
2315 https://ap.org
2316 https://hbs.edu
2317 

2024-07-15 10:46:45,639 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


2368 https://af.mil
2369 https://boutell.co.uk
2370 https://techrepublic.com
2371 https://dropboxusercontent.com
2372 https://jetbrains.com
Error processing URL at index 2373: 2373
2374 https://boutell.com
2375 https://in.pinterest.com
2376 https://atlasobscura.com
2377 https://aka.ms
Error processing URL at index 2378: 2378
2379 https://nielsen.com
2380 https://popularmechanics.com
2381 https://eu.com
2382 https://lifewire.com
2383 https://verywellhealth.com
2384 https://iastate.edu
2385 https://popsci.com
2386 https://termsfeed.com
2387 https://iqiyi.com
2388 https://liveabout.com
2389 https://udel.edu
2390 https://gwu.edu
2391 https://purl.org
2392 https://notion.so
2393 https://vanderbilt.edu
2394 https://zlib.net
2395 https://dhl.com
Error processing URL at index 2396: 2396
2397 https://buzzsprout.com
2398 https://google.com.hk
2399 https://wired.co.uk
2400 https://bankrate.com
2401 https://vorsfelde-live.de
2402 https://dallasnews.com
2403 https://colostate.edu
2404 https://wamps

2024-07-15 10:51:59,631 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


2475 https://lnk.to
2476 https://nsf.gov
2477 https://pbase.com
2478 https://popsugar.com
2479 https://batmanapollo.ru
2480 https://anu.edu.au
2481 https://eia.gov
2482 https://flipboard.com
2483 https://siemens.de
2484 https://mps.gov.cn
2485 https://infogram.com
2486 https://apachelounge.com
2487 https://faa.gov
2488 https://gzip.org
2489 https://alipay.com
2490 https://unam.mx
2491 https://avast.com
2492 https://thespruce.com
2493 https://nerdwallet.com
2494 https://unsw.edu.au
2495 https://ew.com
2496 https://bustle.com
2497 https://tmz.com
2498 https://secureserver.net
2499 https://msdn.com
2500 https://ec-lyon.fr
2501 https://hardened-php.net
2502 https://archdaily.com
2503 https://stuff.co.nz
2504 https://genius.com
2505 https://mtv.com
2506 https://centos.org
2507 https://timeweb.ru
2508 https://xmlsoft.org
Error processing URL at index 2509: 2509
2510 https://stitcher.com
2511 https://google.pl
2512 https://eu.org
2513 https://onlamp.com
2514 https://upi.com
2515 https://hpe.c

2024-07-15 11:17:02,982 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


3009 https://boe.es
3010 https://channelnewsasia.com
Error processing URL at index 3011: 3011
3012 https://ucalgary.ca
3013 https://thenationalnews.com
3014 https://epfl.ch
3015 https://aaa.com
3016 https://yoast.com
3017 https://liberation.fr
3018 https://tudelft.nl
3019 https://cbs.com
3020 https://note.com
3021 https://visualcapitalist.com
3022 https://bleacherreport.com
3023 https://ge.com
3024 https://huggingface.co
3025 https://sbnation.com
3026 https://c-span.org
3027 https://uni-heidelberg.de
3028 https://yorku.ca
3029 https://macworld.com
3030 https://screenrant.com
3031 https://theaustralian.com.au
3032 https://tampabay.com
3033 https://tradingeconomics.com
3034 https://rbc.ru
3035 https://zoom.com
3036 https://web.id
3037 https://httpwg.org
3038 https://bitcoin.org
3039 https://fu-berlin.de
3040 https://packagist.org
3041 https://kff.org
3042 https://bnf.fr
3043 https://lowes.com
3044 https://yomiuri.co.jp
Error processing URL at index 3045: 3045
3046 https://marca.com
3047 

2024-07-15 11:22:06,932 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


3107 https://sapo.pt
3108 https://pandora.com
3109 https://chronicle.com
3110 https://phpmyadmin.net
3111 https://www.bl.uk
3112 https://aappublications.org
3113 https://realsimple.com
Error processing URL at index 3114: 3114
3115 https://archive.is
3116 https://study.com
3117 https://bl.uk
3118 https://meti.go.jp
3119 https://maine.gov
3120 https://bayern.de
3121 https://bfmtv.com
3122 https://vine.co
3123 https://site123.me
3124 https://google.com.ua
3125 https://openedition.org
3126 https://news24.com
3127 https://toptal.com
3128 https://google.se
3129 https://eset.com


2024-07-15 11:22:56,599 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


3130 https://dev.to
3131 https://unity3d.com
3132 https://malwarebytes.com
3133 https://twitpic.com
3134 https://acast.com
3135 https://geeksforgeeks.org
3136 https://wmo.int
3137 https://rambler.ru
3138 https://va.us
3139 https://infoworld.com
3140 https://theknot.com
3141 https://emojipedia.org
3142 https://wolframalpha.com
3143 https://csiro.au
3144 https://cloudwaysapps.com
3145 https://msk.ru
3146 https://geocities.jp
3147 https://aip.org
3148 https://elementor.com
3149 https://thecut.com
3150 https://experian.com
3151 https://nfpa.org
3152 https://glamour.com
3153 https://kriesi.at
3154 https://pingdom.com
3155 https://cc.com
3156 https://kommersant.ru


2024-07-15 11:24:06,054 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


3157 https://tawk.to
3158 https://ask.com
3159 https://codecanyon.net
3160 https://symfony.com
3161 https://ansa.it
3162 https://pinterest.ca
3163 https://g2.com
3164 https://newsday.com
3165 https://usmagazine.com
3166 https://iaea.org
3167 https://wakelet.com
3168 https://newegg.com
3169 https://lesechos.fr
3170 https://openlibrary.org
3171 https://a.co
3172 https://hetzner.com
3173 https://storify.com
3174 https://blurb.com
3175 https://haproxy.org
3176 https://mathworks.com
3177 https://gmw.cn
3178 https://termly.io
3179 https://bartleby.com
3180 https://complex.com
3181 https://ab.ca
3182 https://berlin.de
3183 https://cnki.net
3184 https://real.com
3185 https://page.line.me
3186 https://doodle.com
3187 https://flippingbook.com
3188 https://emptyhammock.com
3189 https://weibo.cn
3190 https://ucoz.ru
3191 https://adidas.com
3192 https://wikiwand.com
3193 https://miami.edu
3194 https://complianz.io
3195 https://allmusic.com
3196 https://rit.edu
3197 https://diabetes.org
3198 https:/

2024-07-15 11:36:52,489 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


3501 https://google.gr
3502 https://kqed.org
3503 https://avaaz.org
3504 https://foreignaffairs.com
3505 https://oberlo.com
3506 https://bloomberglaw.com
3507 https://metacritic.com
3508 https://canalblog.com
3509 https://tn.gov
3510 https://nngroup.com
3511 https://hku.hk
3512 https://me.com
3513 https://plusone.google.com
3514 https://healthcare.gov
3515 https://gencat.cat
3516 https://ctfassets.net
3517 https://csis.org
3518 https://disneyplus.com
3519 https://sltrib.com
3520 https://vam.ac.uk
3521 https://designboom.com
Error processing URL at index 3522: 3522
3523 https://geocaching.com
3524 https://wikileaks.org
3525 https://splashthat.com
3526 https://ku.dk
3527 https://msu.ru
3528 https://nottingham.ac.uk
3529 https://checkpoint.com
3530 https://st-andrews.ac.uk
3531 https://thekitchn.com
3532 https://geekwire.com
3533 https://countryliving.com
3534 https://financialexpress.com
3535 https://dc.gov
Error processing URL at index 3536: 3536
3537 https://capgemini.com
3538 https://

2024-07-15 11:39:46,010 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


3560 https://home.kpmg
3561 https://abebooks.com
3562 https://christies.com
3563 https://battle.net
3564 https://wbs.legal
3565 https://case.edu
3566 https://tsa.gov


2024-07-15 11:40:07,439 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


3567 https://google.pt
3568 https://sitepoint.com
3569 https://ub.edu
3570 https://jooble.org
3571 https://mb.ca
3572 https://esteri.it
3573 https://zerohedge.com
3574 https://stltoday.com
3575 https://mindbodygreen.com
3576 https://newsmax.com
3577 https://kyoto-u.ac.jp
3578 https://careerbuilder.com
3579 https://repec.org
3580 https://radiofrance.fr
3581 https://people.cn
3582 https://recaptcha.net
3583 https://yle.fi
3584 https://zippia.com
3585 https://guidestar.org
3586 https://wpzoom.com
3587 https://drexel.edu
Error processing URL at index 3588: 3588
3589 https://ionos.de
3590 https://payscale.com
3591 https://american.edu
3592 https://cato.org
3593 https://amnh.org
3594 https://britishairways.com
3595 https://intensedebate.com
3596 https://fortinet.com
3597 https://cuhk.edu.hk
3598 https://tkqlhce.com
3599 https://google.dk
3600 https://kaggle.com
3601 https://networkworld.com
3602 https://jalopnik.com
3603 https://thediplomat.com
3604 https://unh.edu
3605 https://mcmaster.ca
3

2024-07-15 11:58:00,675 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4026 https://google.com.vn


2024-07-15 11:58:11,510 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


4027 https://gob.ec
4028 https://linuxfoundation.org
4029 https://awwwards.com
4030 https://viber.com
4031 https://dispatch.com
4032 https://lexology.com
4033 https://nv.gov
4034 https://here.com
4035 https://sina.cn
4036 https://eugdpr.org
4037 https://fortunecity.com
4038 https://state.co.us
4039 https://acuityscheduling.com
4040 https://plannedparenthood.org
Error processing URL at index 4041: 4041
4042 https://mensjournal.com
4043 https://torontosun.com
4044 https://thedrive.com
4045 https://audubon.org
4046 https://gob.cl
4047 https://runnersworld.com
4048 https://nrel.gov
4049 https://brides.com
4050 https://macmillan.com
4051 https://prf.hn
4052 https://okstate.edu
4053 https://investors.com
4054 https://unrealengine.com
Error processing URL at index 4055: 4055
4056 https://basf.com
4057 https://pxf.io
4058 https://familysearch.org
4059 https://tuwien.ac.at


2024-07-15 11:59:23,972 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4060 https://vaticannews.va
4061 https://ic3.gov
4062 https://transportation.gov
4063 https://getresponse.com
4064 https://roku.com
4065 https://lexpress.fr
4066 https://regulations.gov
Error processing URL at index 4067: 4067
4068 https://opendemocracy.net
4069 https://quantcast.com
4070 https://cision.com
4071 https://microchip.com
4072 https://georgia.gov
Error processing URL at index 4073: 4073
4074 https://findarticles.com
4075 https://eldiario.es
4076 https://rki.de
4077 https://ma.us
4078 https://hypebeast.com


2024-07-15 12:01:33,666 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4079 https://google.com.ph
4080 https://att.net
4081 https://health.gov.au
4082 https://cloudways.com
4083 https://cbinsights.com
4084 https://au.dk
4085 https://fotolia.com
4086 https://uib.no
4087 https://nh.gov
4088 https://wholefoodsmarket.com
Error processing URL at index 4089: 4089
4090 https://acronis.com
4091 https://delish.com
4092 https://wur.nl
4093 https://google.cl
4094 https://proboards.com
4095 https://bis.org
4096 https://newsobserver.com
4097 https://sothebys.com
4098 https://europeana.eu
4099 https://poynter.org
4100 https://doc.gov
4101 https://basecamp.com
4102 https://chip.de
4103 https://ada.gov
4104 https://analog.com
4105 https://crunchyroll.com
4106 https://meltwater.com
4107 https://audacityteam.org
4108 https://gothamist.com
4109 https://studentaid.gov
4110 https://gazeta.ru
4111 https://mhanational.org
4112 https://etonline.com
4113 https://clutch.co
4114 https://fmprc.gov.cn
4115 https://mix.com
4116 https://audacy.com
4117 https://nos.nl
4118 https://awebe

2024-07-15 12:06:34,860 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out
2024-07-15 12:06:34,867 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2024-07-15 12:06:34,885 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4167 https://bnnbloomberg.ca
4168 https://pastelink.net
4169 https://rediff.com
4170 https://wpenginepowered.com
4171 https://ssl-images-amazon.com
4172 https://beacons.ai
4173 https://project-syndicate.org
4174 https://themuse.com
4175 https://sierraclub.org
4176 https://jpn.org
4177 https://desmoinesregister.com
4178 https://cincinnati.com
4179 https://surrey.ac.uk
4180 https://youdao.com
4181 https://20minutes.fr
4182 https://interestingengineering.com
4183 https://ultimate-guitar.com
4184 https://yna.co.kr
4185 https://megaupload.com
4186 https://bit.do
4187 https://www.gov.pl
4188 https://acpjournals.org
4189 https://e-monsite.com
4190 https://broadwayworld.com
4191 https://reverso.net
4192 https://scitation.org
4193 https://tidal.com
4194 https://templatemonster.com
4195 https://googlesyndication.com
4196 https://tu-berlin.de
4197 https://whatwg.org
4198 https://tapatalk.com
4199 https://steemit.com
4200 https://interfax.ru
4201 https://amtrak.com
4202 https://tensorflow.org
4203

2024-07-15 12:13:01,848 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


4348 https://onelink.to
Error processing URL at index 4349: 4349
4350 https://mdr.de
Error processing URL at index 4351: 4351
4352 https://techsmith.com
4353 https://escholarship.org
4354 https://redd.it
4355 https://dwcdn.net
4356 https://domain.com
4357 https://unibe.ch
4358 https://nttexpress.com
4359 https://uab.edu
4360 https://skynet.be
4361 https://nrk.no
4362 https://ucoz.com
4363 https://campaignmonitor.com
4364 https://eyoucms.com
4365 https://cracked.com
4366 https://researchandmarkets.com
4367 https://metal-archives.com
4368 https://autonews.com
4369 https://hubspotusercontent-na1.net
4370 https://grammy.com
4371 https://zenwriting.net
4372 https://pdx.edu
Error processing URL at index 4373: 4373
4374 https://techtimes.com
4375 https://estadao.com.br
4376 https://uw.edu.pl
4377 https://smartinsights.com
4378 https://podomatic.com
4379 https://bestwestern.com
4380 https://hasbro.com
4381 https://wisconsin.gov
4382 https://southernliving.com
4383 https://ssllabs.com
4384 http

2024-07-15 12:15:52,125 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4412 https://j.mp
4413 https://koreatimes.co.kr
4414 https://dokuwiki.org
4415 https://writeablog.net
4416 https://nrf.com
4417 https://globalresearch.ca
4418 https://cheezburger.com
4419 https://blossomthemes.com
4420 https://nocookie.net
4421 https://google.rs
4422 https://urban.org


2024-07-15 12:16:12,391 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4423 https://archive.ph
4424 https://donorbox.org
4425 https://corporatefinanceinstitute.com
4426 https://psychiatryonline.org
4427 https://ameba.jp
4428 https://webopedia.com
4429 https://rtl.de
4430 https://company.site
4431 https://thehackernews.com
4432 https://marinetraffic.com
4433 https://usask.ca
4434 https://website-files.com
4435 https://knightlab.com
4436 https://uni-freiburg.de
4437 https://opentext.com
4438 https://deutschlandfunk.de
4439 https://adjust.com
4440 https://nga.gov
4441 https://avma.org
4442 https://home.pl
4443 https://taylorandfrancis.com
4444 https://amazon.cn
4445 https://privacypolicies.com
4446 https://oscars.org
4447 https://unglobalcompact.org
4448 https://milb.com
4449 https://copernicus.org
4450 https://zohopublic.com
4451 https://blm.gov
4452 https://inquisitr.com
4453 https://carleton.ca
4454 https://gouvernement.fr
4455 https://ufmg.br
4456 https://jetpack.com
4457 https://adac.de
4458 https://env.go.jp
4459 https://bath.ac.uk
4460 https://vermont

2024-07-15 12:22:28,748 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4593 https://dtic.mil
4594 https://city-data.com
4595 https://ebsco.com
4596 https://imgbb.com
4597 https://hpage.com


2024-07-15 12:22:34,646 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4598 https://google.com.eg
Error processing URL at index 4599: 4599
Error processing URL at index 4600: 4600
4601 https://anotepad.com
4602 https://fujifilm.com
4603 https://heyzine.com
4604 https://websitedemos.net
4605 https://courthousenews.com
4606 https://koreaherald.com
4607 https://google.hr
4608 https://threadless.com
4609 https://vocabulary.com
4610 https://fairmont.com
4611 https://google.com.pk
4612 https://9to5google.com
4613 https://pscp.tv
4614 https://sportskeeda.com
4615 https://thejakartapost.com
4616 https://charitynavigator.org
4617 https://gale.com
4618 https://neurology.org
4619 https://theinformation.com
4620 https://newindianexpress.com
4621 https://casetext.com
4622 https://oohcams.com
4623 https://metrika.yandex.ru
4624 https://androidcentral.com
4625 https://comicbook.com
4626 https://taplink.cc
4627 https://io9.com
4628 https://huji.ac.il
4629 https://pastemagazine.com
4630 https://mn.co
4631 https://aao.org
4632 https://bts.gov
4633 https://esy.es
4634 https

2024-07-15 12:36:15,067 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4903 https://db.tt
4904 https://eiu.com
4905 https://wsws.org
4906 https://wiwo.de
4907 https://equifax.com
4908 https://rusgrappling.ru
4909 https://tinypng.com
4910 https://ffmpeg.org
4911 https://shop-pro.jp
4912 https://abc7ny.com
4913 https://mostbeter.com
4914 https://albany.edu
4915 https://ucpress.edu
4916 https://discourse.org
4917 https://nrc.nl
4918 https://courier-journal.com
4919 https://ulule.com
4920 https://constantcontactpages.com
4921 https://christianpost.com
Error processing URL at index 4922: 4922
4923 https://undocs.org
4924 https://vulkan-vegas.de
4925 https://stonybrook.edu
4926 https://yubico.com
4927 https://xuexi.cn
4928 https://coolors.co
4929 https://carbonbrief.org
4930 https://ces.tech
4931 https://vulkan-vegas-deutschland.com
4932 https://google.by
4933 https://star-telegram.com
4934 https://cozaarinfo.com
4935 https://depakoteinfo.com
4936 https://iht.com
4937 https://app.impact.com
4938 https://upf.edu
4939 https://w3techs.com
4940 https://rainn.org
49

2024-07-15 12:43:24,014 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5132 https://uscg.mil
5133 https://nongnu.org
5134 https://su.se
5135 https://c2.com
5136 https://wilsoncenter.org
5137 https://roll20.net
5138 https://wpml.org
5139 https://slashfilm.com
5140 https://icbc.com.cn
5141 https://zimbio.com
5142 https://paulgraham.com
5143 https://ms.us
5144 https://hostelworld.com
5145 https://boots.com
5146 https://builtin.com
5147 https://ntu.edu.sg
5148 https://radikal.ru
5149 https://la.gov
5150 https://sucuri.net
5151 https://cadenaser.com
5152 https://businesstoday.in
5153 https://ok.gov
5154 https://hessen.de
5155 https://lightwidget.com
5156 https://ansi.org
5157 https://nwf.org
5158 https://salute.gov.it
5159 https://walkscore.com
5160 https://unirioja.es
5161 https://marketscreener.com
5162 https://defensenews.com
5163 https://openbsd.org
5164 https://ntv.co.jp
5165 https://mobygames.com
5166 https://atw.hu
5167 https://bmwk.de
5168 https://united-domains.de
5169 https://lush.com
5170 https://cbr.com
Error processing URL at index 5171: 5171
5172

2024-07-15 12:46:58,853 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5214 https://darpa.mil
5215 https://thecrimson.com
5216 https://lasvegassun.com
5217 https://wallethub.com
5218 https://urbanoutfitters.com
5219 https://kb.plesk.com
5220 https://triblive.com
5221 https://yourstory.com
5222 https://guggenheim.org
5223 https://kharkov.ua
5224 https://uts.edu.au
5225 https://cephalexininfo24.com
Error processing URL at index 5226: 5226
5227 https://middleeasteye.net
5228 https://court.gov.cn
5229 https://tripadvisor.in
5230 https://doi.gov
5231 https://usyd.edu.au
5232 https://dailysabah.com
5233 https://workers.dev
5234 https://oraclecloud.com
5235 https://smore.com
5236 https://uea.ac.uk
5237 https://universetoday.com
5238 https://france.tv
5239 https://starwoodhotels.com
5240 https://pubhtml5.com
Error processing URL at index 5241: 5241
5242 https://jma.go.jp
5243 https://bpb.de
5244 https://niu.edu
5245 https://opm.gov


2024-07-15 12:48:01,677 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


5246 https://up.pt
5247 https://scu.edu
5248 https://postandcourier.com
5249 https://audioboom.com
5250 https://chegg.com
5251 https://thejournal.ie
5252 https://maff.go.jp
5253 https://qatarairways.com
5254 https://uk.net
5255 https://umblr.com
5256 https://abdn.ac.uk
5257 https://sd.gov
5258 https://aph.gov.au
5259 https://conta.cc
5260 https://qut.edu.au
5261 https://netsuite.com
5262 https://nyti.ms
5263 https://iherb.com
5264 https://librarything.com
5265 https://leetcode.com
Error processing URL at index 5266: 5266
5267 https://autismspeaks.org
5268 https://novartis.com


2024-07-15 12:49:12,621 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


5269 https://google.com.ec
5270 https://repaglinideinfo.com
5271 https://suse.com
5272 https://ramseysolutions.com
5273 https://indymedia.org
5274 https://augmentinbik.com
5275 https://hubblesite.org
5276 https://google.com.bd
5277 https://infoactos.com
5278 https://confex.com
5279 https://nhc.gov.cn
5280 https://rootsweb.com
5281 https://mordorintelligence.com
5282 https://gabapentininfo24.com
5283 https://unipi.it
5284 https://snap.com
5285 https://tas.gov.au
5286 https://robaxininfo.com
5287 https://mydrivers.com
5288 https://phonearena.com
5289 https://turkishairlines.com
5290 https://wa.us
5291 https://remeroninfo.com
5292 https://ncaa.com
5293 https://acarboseinfo.com
5294 https://rust-lang.org
5295 https://themarginalian.org
5296 https://protonixinfo.com
5297 https://doodleordie.com
5298 https://diclofenacinfo.com
5299 https://uct.ac.za
5300 https://ntnu.no
5301 https://fitchratings.com
5302 https://htc.com
5303 https://infoabilify.com
5304 https://fastcodesign.com
5305 https://

2024-07-15 12:53:23,178 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


5370 https://google.com.uy
5371 https://deveducation.com
5372 https://avira.com
5373 https://icao.int
5374 https://merck.com
5375 https://sony.net
5376 https://sae.org
5377 https://kantei.go.jp
5378 https://rian.ru
5379 https://mnn.com
5380 https://montana.edu
5381 https://goodrx.com
5382 https://wellandgood.com
5383 https://freeservers.com
5384 https://ukri.org
5385 https://radio.com
5386 https://renren.com
5387 https://bhf.org.uk
5388 https://jneurosci.org
5389 https://prospect.org
5390 https://aalto.fi
5391 https://latribune.fr
5392 https://sennheiser.com
5393 https://no-ip.org
5394 https://casino-glory.com
5395 https://mindspring.com
5396 https://cvs.com
5397 https://imgflip.com
5398 https://vesti.ru
5399 https://1tv.ru
5400 https://cbr.ru
5401 https://funnyordie.com
5402 https://king5.com
5403 https://unilever.com
5404 https://dnspod.cn
5405 https://blogfreely.net
5406 https://kent.ac.uk
5407 https://google.ee
5408 https://rijksmuseum.nl
5409 https://az.gov
5410 https://uni-mainz.

2024-07-15 12:58:11,835 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5430 https://google.ba


2024-07-15 12:58:13,066 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5431 https://google.com.gt
5432 https://liverpoolecho.co.uk
5433 https://transunion.com
5434 https://gatesnotes.com
Error processing URL at index 5435: 5435
5436 https://wordpressfoundation.org
5437 https://mozdev.org
5438 https://slideserve.com
5439 https://umu.se
5440 https://infosemaglutide.com
5441 https://scitechdaily.com
5442 https://cao.go.jp
5443 https://kroger.com
5444 https://ns.ca
5445 https://rdcu.be
5446 https://iii.org
5447 https://22.cn
5448 https://theodysseyonline.com
5449 https://pri.org
5450 https://uni-bremen.de
5451 https://spokesman.com
Error processing URL at index 5452: 5452
5453 https://live.staticflickr.com
5454 https://printfriendly.com
5455 https://google.com.ng
5456 https://utdallas.edu
5457 https://merchantcircle.com
5458 https://manutd.com
5459 https://barcelona.cat
5460 https://jrj.com.cn
5461 https://ottawacitizen.com
5462 https://nt.gov.au
5463 https://nyt.com
5464 https://govtech.com
5465 https://mouser.com
5466 https://allevents.in
5467 https://gamer

2024-07-15 13:08:13,119 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5626 https://google.bs
5627 https://rappler.com
5628 https://unicamp.br
5629 https://jaxa.jp
5630 https://collegehumor.com
5631 https://netlify.com
5632 https://fr.de
5633 https://wfaa.com
5634 https://tianqi.com
5635 https://icij.org
5636 https://healthdata.org
5637 https://jmir.org
5638 https://mostbet-az24.com
5639 https://asha.org
5640 https://chathamhouse.org
Error processing URL at index 5641: 5641
5642 https://climate.gov
5643 https://dilbert.com
5644 https://blog.youtube
5645 https://mindmeister.com
5646 https://8m.com
5647 https://cert.org
5648 https://ncaa.org
5649 https://optimole.com
5650 https://wp.pl
5651 https://nikkei.co.jp
5652 https://podchaser.com
5653 https://fanpop.com
5654 https://golem.de
5655 https://taipeitimes.com
5656 https://16personalities.com
5657 https://net-a-porter.com
5658 https://lehigh.edu
5659 https://globalcitizen.org
5660 https://ubuntuforums.org
Error processing URL at index 5661: 5661
5662 https://wisegeek.com
5663 https://cleverreach.com
5664 h

2024-07-15 13:11:46,616 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5707 https://google.lk
5708 https://movieweb.com
5709 https://edf.org
Error processing URL at index 5710: 5710
5711 https://louisiana.gov
5712 https://rsna.org
5713 https://nintendo.co.jp
5714 https://kongregate.com
5715 https://techpowerup.com
5716 https://wfu.edu
5717 https://uniroma1.it
5718 https://tribuneindia.com
5719 https://ig.com.br
5720 https://nintendolife.com


2024-07-15 13:12:10,817 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


5721 https://ffm.to
5722 https://komonews.com
5723 https://harpers.org
5724 https://f-droid.org
5725 https://rotary.org
Error processing URL at index 5726: 5726
5727 https://gob.ve
5728 https://thehotline.org
5729 https://pin-up-com.ru
5730 https://government.nl
5731 https://fandango.com
5732 https://fes.de
5733 https://sched.com
5734 https://ufrj.br
5735 https://progress.com
5736 https://hgtv.co.uk
5737 https://dropout.tv
5738 https://senat.fr
5739 https://efe.com
5740 https://mostbetsport.kz
5741 https://cervantes.es
5742 https://creative.com
5743 https://36kr.com
5744 https://fortunebusinessinsights.com
5745 https://dow.com
5746 https://bio.link
5747 https://cirquedusoleil.com
5748 https://simplilearn.com
5749 https://irena.org
5750 https://iconfinder.com
5751 https://greenhouse.io
5752 https://buzzsumo.com
5753 https://massgeneral.org


2024-07-15 13:13:41,796 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


5754 https://solo.to
5755 https://lboro.ac.uk
5756 https://blogspot.se
5757 https://fanfiction.net
5758 https://avid.com
5759 https://glaad.org
5760 https://festival-cannes.com
5761 https://europe1.fr
5762 https://jp.net
5763 https://aau.dk
5764 https://dzwww.com
5765 https://us.es
5766 https://khou.com
Error processing URL at index 5767: 5767
5768 https://rss.com


2024-07-15 13:13:58,811 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5769 https://osd.mil
5770 https://governo.it
5771 https://ccleaner.com
5772 https://opensource.com
5773 https://uni-trier.de
5774 https://motorsport.com
5775 https://json.org
5776 https://paramount.com
5777 https://thewire.in
5778 https://draxe.com
5779 https://google.co.bw
5780 https://avvo.com
5781 https://bestlifeonline.com
5782 https://usccb.org
5783 https://demilked.com
5784 https://infusionsoft.com
5785 https://richmond.com
5786 https://ecosoberhouse.com
5787 https://conac.cn
5788 https://dion.ne.jp
5789 https://deseretnews.com
5790 https://ind.br
5791 https://ruhr-uni-bochum.de
5792 https://nebraska.gov
5793 https://ifc.org
5794 https://strath.ac.uk
5795 https://toronto.edu
5796 https://devowl.io
5797 https://rada.gov.ua
5798 https://comparitech.com
5799 https://ucd.ie
5800 https://gazzetta.it
Error processing URL at index 5801: 5801
5802 https://jpmorganchase.com
5803 https://southcn.com
5804 https://jamendo.com
5805 https://skift.com
5806 https://animoto.com
5807 https://keepa

2024-07-15 13:15:23,633 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5809 https://google.com.mt
5810 https://corporate-ir.net
5811 https://adblockplus.org
Error processing URL at index 5812: 5812
5813 https://clickcease.com
5814 https://snazzymaps.com
5815 https://osaka-u.ac.jp
5816 https://delltechnologies.com
5817 https://actionnetwork.org
5818 https://usajobs.gov
5819 https://thefederalist.com
5820 https://moonfruit.com
5821 https://jasonebin.com
5822 https://chop.edu
5823 https://singaporeair.com
5824 https://babbel.com
5825 https://rxlist.com
5826 https://myswitzerland.com
5827 https://lendingtree.com
5828 https://la-croix.com
5829 https://rospotrebnadzor.ru
5830 https://activestate.com
5831 https://wsbtv.com
5832 https://berliner-zeitung.de
5833 https://hackerone.com
5834 https://sgs.com
5835 https://wwe.com
5836 https://amerio.bet
5837 https://lrb.co.uk
5838 https://myminifactory.com
Error processing URL at index 5839: 5839
5840 https://xoom.com
5841 https://rockpapershotgun.com
5842 https://googlesource.com


2024-07-15 13:16:50,595 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5843 https://google.ad
5844 https://prosieben.de
5845 https://treas.gov
5846 https://uni-hannover.de
5847 https://grafana.com
5848 https://sante.fr
5849 https://hypermart.net
5850 https://ticksy.com
5851 https://codeberg.org


2024-07-15 13:17:21,101 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5852 https://google.com.pa
5853 https://yaml.org


2024-07-15 13:17:22,494 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5854 https://google.com.sv
5855 https://restaurantguru.com
5856 https://art.br
5857 https://kuaishou.com
5858 https://lithub.com
5859 https://washingtonian.com
5860 https://listennotes.com
5861 https://ellenmacarthurfoundation.org
5862 https://sciencefocus.com
Error processing URL at index 5863: 5863
5864 https://ui.ac.id
5865 https://bugs.mysql.com
5866 https://wellfound.com
5867 https://womansday.com
5868 https://blog.br
5869 https://euobserver.com
5870 https://bcorporation.net
Error processing URL at index 5871: 5871
5872 https://39.net
5873 https://rr.com
5874 https://rhizome.org
5875 https://tucows.com
5876 https://ixbt.com
5877 https://futura-sciences.com
5878 https://savethechildren.org
5879 https://ademe.fr
5880 https://sparknotes.com
5881 https://japantoday.com
5882 https://exxonmobil.com
5883 https://google.bi
5884 https://kurier.at
5885 https://google.ci
5886 https://iospress.com
5887 https://azlyrics.com
5888 https://comptia.org
5889 https://corel.com
5890 https://npc.gov.c

2024-07-15 13:19:27,912 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5904 https://ahram.org.eg
5905 https://detik.com
5906 https://geogebra.org
Error processing URL at index 5907: 5907
5908 https://google.com.ly
5909 https://psmag.com
5910 https://zebra.com
5911 https://google.com.np
5912 https://omaha.com
5913 https://cafelog.com
5914 https://unibas.ch
5915 https://al-monitor.com
5916 https://onlinehome.us
5917 https://artnews.com
5918 https://e2ma.net
5919 https://sachsen.de


2024-07-15 13:19:49,200 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5920 https://google.cg
5921 https://tv-asahi.co.jp
5922 https://umb.edu
5923 https://binghamton.edu


2024-07-15 13:20:11,057 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


5924 https://gub.uy
5925 https://thewaltdisneycompany.com
5926 https://victoriassecret.com
5927 https://questionpro.com
Error processing URL at index 5928: 5928
5929 https://princetonreview.com
5930 https://opb.org
5931 https://jhsph.edu
5932 https://ucc.ie
5933 https://break.com
5934 https://agu.org
5935 https://eetimes.com
5936 https://gnavi.co.jp
5937 https://denofgeek.com
5938 https://nespresso.com
5939 https://tineye.com
5940 https://publicradio.org
5941 https://www.ne.jp
5942 https://jacksonville.com
5943 https://uba.ar
5944 https://veeam.com
5945 https://bepress.com
5946 https://google.ge
5947 https://dreamhosters.com
5948 https://bravenet.com


2024-07-15 13:21:37,977 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


5949 https://google.dz
5950 https://gazzettaufficiale.it
5951 https://highsnobiety.com
5952 https://wwnorton.com
5953 https://fudan.edu.cn
5954 https://google.cat
5955 https://umaine.edu
5956 https://mercer.com
5957 https://nysed.gov
5958 https://invisionapp.com
5959 https://rlp.de
5960 https://dynadot.com
5961 https://uwyo.edu
5962 https://blubrry.com
5963 https://random.org
5964 https://zenbusiness.com
5965 https://thelocal.se
5966 https://hackster.io
5967 https://fau.edu
5968 https://nbcphiladelphia.com
5969 https://cheatsheet.com
5970 https://bethesda.net
5971 https://google.co.ck
5972 https://kompas.com
5973 https://globalsign.com
5974 https://asahi-net.or.jp
5975 https://muenchen.de
5976 https://ga.us
5977 https://curtin.edu.au
5978 https://couriermail.com.au
5979 https://canoe.ca
5980 https://igi-global.com
5981 https://joelonsoftware.com
5982 https://smartrecruiters.com
5983 https://city.ac.uk
5984 https://stores.jp
5985 https://google.com.ag
5986 https://thisamericanlife.org
5

In [45]:
#converting the list to dataframe
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection', 
                 'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Domain_Age', 
                 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards',
                 'Label']

legitimate = pd.DataFrame(legi_features, columns= feature_names)
legitimate.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0          dewatergroep.be        0        0           0          0   
1             poppankki.fi        0        0           0          0   
2            ceskaposta.cz        0        0           0          0   
3  suncoastcreditunion.com        0        0           0          0   
4                   caf.fr        0        0           0          0   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Domain_Age  \
0            0             0        0              0           0          12   
1            0             0        0              0           0          14   
2            0             0        0              0           1           1   
3            0             0        0              0           0          21   
4            0             0        0              0           0          26   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           0       1           0            0             0      0  
1           0       0           0            0             0      0  
2           1       0           0            0             1      0  
3           0       0           0            0             0      0  
4           0       0           0            0             0      0

Części z adresów URL nie udało się przetworzyć, w wyniku czego wyodrębniliśmy cechy 5783 bezpiecznych stron. Informacje o błędach zostały zapisane do pliku log.txt.

In [46]:
# Storing the extracted legitimate URLs fatures to csv file
legitimate.to_csv('legitimate.csv', index= False)

### 4.2. Adresy phishingowe:
Ekstrakcja funkcji zostaje przeprowadzana dla adresów URL stron phishingowych.

In [47]:
phishurl.shape

(6000, 1)

In [48]:
#Extracting the feautres & storing them in a list
phish_features = []
label = 1
for i in range(phishurl.shape[0]):
  try:
    url = phishurl['url'][i]
    phish_features.append(featureExtraction(url,label))
    print(i, url)
  except Exception as e:
    print(f"Error processing URL at index {i}: {e}")
    with open('log2.txt', 'a') as f:
        f.write(f"Error processing URL at index {i}: {e}\n")
    continue

0 https://doiw0zuhcw9rosjhic.pages.dev/smart89/
1 https://ipfs.io/ipfs/bafkreiahpgxlkqme2bhj5jfivspo6mfawwcwnlp3hx7ig2432osdya2da4
2 https://cloudflare-ipfs.com/ipfs/bafkreiahpgxlkqme2bhj5jfivspo6mfawwcwnlp3hx7ig2432osdya2da4
3 https://start-a-complaint-meta-01061657.pages.dev/
4 https://distritonorte.com.mx/js/config/login.php/
5 https://pub-dc4276801daa4b3cb0fcdc86b134bf2e.r2.dev/cap1.html


2024-07-15 13:24:48,769 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


6 https://trimmer.to/uuhmU
7 http://soodaryan.github.io/spotify-web-player-clone
8 https://homepage--sso-kucoin.webflow.io/
9 https://suitee-trezr-app-apps.webflow.io/
10 https://sso-m-robinhoods----com-autth.webflow.io/
11 https://usapholdlogin-1.gitbook.io/eu
12 https://usupheld-lugni.gitbook.io/us
13 https://mettamask--exxtnson-chrome.gitbook.io/us
14 https://www.metaappealform.com/metahelp/
15 https://3656ee.com:8989/mobile-client/bet365_627/index.html?td_channelid=627
16 https://meittamaxlogiin.gitbook.io/us
17 https://dana-van.danakitakan.my.id/
18 https://meine-commerz-phototan-aktualisierung.top/
19 https://www.instagram.com.sg3.sosis-berurat.works/
20 https://www.instagram.com.sg1.sosis-berurat.works/
21 https://indranilpaul15.github.io/netflix-clone
22 https://mdfaizan-786.github.io/Netflix-Clone
23 https://matamsklogin.gitbook.io/us
24 http://claim-dana-kaget.pages.dev/
25 https://free.aslvpn.loseyourip.com/
26 https://visitor132677.com/
27 https://whatsapp-kf.top/
28 https:

2024-07-15 13:35:32,586 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


416 https://rb.gy/ykeeqj
417 https://royal-glade-286f.kdsj.workers.dev/privacy/index.php
418 https://www.xuyvdj.com/
419 https://skype-sg.net/
420 https://zigutayoicbj.orbit321.one/index.php
421 http://cf.hk.1111r.icu/
422 http://claimz-dana-kagetzx4.t-4.my.id/
423 http://suite-en-trezor.github.io/us
424 http://skyaldwin.acrif.my.id/
425 http://netflixacademy.kr/
426 https://ipfs.io/ipfs/bafybeieab2k7k4ryxpjiyubtawe5qqq3kkkqrkvkhsb3qreqbqlimk3bce/index.html/
427 http://microsoft.userid-81d.ws/subscription/yJfnBtCfowt-AV53dwkb-bFjJnW1_Yum9WEw=/XVhduIK4AmMt5YNSpZ59Mzl5iKd_6Hnh
428 http://www.lifeproducti.com/page/4382cf8881be544bba2f0011d2888a712da6a226
429 https://it-corner.co.uk/id
430 https://hadiah.dana.kaget.webappsystem.com/
431 http://telesgrnarn.com/
432 https://www.reviews.bussinesaccount.my.id/
433 https://www.reviews.bussinesaccount.my.id/re.php
434 https://www.reviews.bussinesaccount.my.id/rever.php
435 https://www.reviews.bussinesaccount.my.id/reverse.php
436 https://www.rev

2024-07-15 13:42:38,004 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


649 http://fakeserhelpsreivew-facesonseriengoies-16838.io.vn/
650 https://docs.google.com/presentation/d/e/2PACX-1vRJ89AGCqNKOTsx8LejdxA-1_0CUJNuIYdqR04j6dCJO-hDgOXRxs04VVZObzrCmG9HVPUXMa-eg_WP/pub?start=false&amp;loop=false&amp;delayms=3000
651 https://mgcvuei.wixsite.com/my-site/
652 https://bafybeifvkiwhwznsk6falnousmpmco4lndo3o3we3xfuvdz23rndumljba.ipfs.w3s.link/ogf.html
653 https://storage.cloud.google.com/indettn/pdflmanco.html
654 https://taxx-lux.web.app/
655 http://k25ci3z.duckdns.org
656 https://docs.google.com/drawings/d/1x8rHQgTpMPOtl6mrNERCmnh-YrCVyfKNhGnA3bTdwzY/edit
657 https://qrco.de/bfDJVE
658 https://al-awda.org/
659 https://ipfs.eth.aragon.network/ipfs/bafybeiccj5cf55ruwyu5zyn7jmzu45xj3d4haewvv6p3pta2wpzbqq45nm
660 https://atuokwxfm.web.app/
661 https://hpz.rbc.mybluehost.me/spt
662 https://juno-106689.weeblysite.com/
663 https://ipfs.io/ipfs/QmQB6WpLAm2UFTLB1aJGu7Y5RRt6hg6xnvwQCzSCANeN8m
664 https://sites.google.com/view/hgrghhngge/home
665 https://pub-9bde0e4dc154

2024-07-15 13:43:47,467 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


680 http://ff.member.garerna.vn/
681 https://t.co/9U8L86bGd6
682 http://pancakeswap-alphav3.vercel.app
683 https://cjffjd.com/B9U34g/?t=HNDB6yUJYh
684 https://dappmainet.pages.dev/
685 https://bafybeiccnes4imrcjciw3xrp4dfkc4fx3yncpxcfxsezwxxv2djx3cdtpi.ipfs.cf-ipfs.com/off365webmail-app-access.html
686 https://reztorge.web.app/
687 https://swisspass.sbb-cff.online/
688 http://btsupport-0-1dbl.my.asekio.com/
689 https://slomanidjassa.web.app/
690 https://yahoo-106018.weeblysite.com/
691 https://claredia.com/ico/fio/?2vo14z4vnmd1ony3ojmyga4l
692 https://startupdtodaylamoreforyuz.rosaura588.workers.dev/64ecb90869f5c7b4ec253184/om/Ye3ZnkXNp?sso_reload=true
693 https://oix.454812452.xyz/zbjj17bt/BgJM6W/7
694 https://pub-4d97631662434b85845e7be2b52b6e61.r2.dev/glennhoulier2023.html
695 https://ojxmgaa.cn/64NMEIUJ/
696 https://bafybeienvgimp6nkbpncoybghc4l4unmlvzzwl2xfdvtrcbuo55phy23wy.ipfs.w3s.link/rinindex.html
697 http://ok.uz.ua/0t
698 https://hello-world-lively-night-2b68.nugnojilti.work

2024-07-15 13:49:04,079 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


885 https://tyny.to/s125de
886 https://q1-238.firebaseapp.com/
887 https://ln.run/fU0sR
888 https://ipfs.io/ipfs/QmVGZSQB6VuPXCQQzjFKf77mq4orRsKuqDHk9aEdZ4PvXi/valuesadder.html
889 https://docs.google.com/presentation/d/e/2PACX-1vTkHTfbEg803_YunQkSSXbuK3_NrQX55jaVf0YwcawmbeEoXAJm8sCZyKiXTNHcxc4idDjx9DYMyKbK/pub?start=true&amp;loop=true&amp;delayms=1000
890 https://sonatahouse.school/?msgid=aHcxWUdBdTVWQlpEeEpUTldKa3RVYjUzZGtXQ3V1MlVjdUdCMDQyenprS1dxbFN0enJqc2ZzczJQNzM0VGwvQUppZ2c1TlVMaGt2OHVGRW9JNFBDeXJmd3ZMZ204NWduTnJiT3A2MnhQUHJzNFU4UExzTFp4ekNDcitMQnhPRCs%3D
891 https://metamaskafe.azurewebsites.net
892 https://sites.google.com/view/dhegherjhyerhjre/home?authuser=1
893 https://cloudflare-ipfs.com/ipfs/bafybeieegiadkphg3njmeaa4ys6uitpasigc46kac4lv6xkzxp3qfzxldm/autpstatementpdfBOXTOBOXX.html
894 https://docs.google.com/presentation/d/e/2PACX-1vTPRoxWNudVsoYvgl1J0H8a0UkLVbxX1_24ucEfE4kS8O72My8FXq8YtbKuzcd5N7WlMC91aOT7VBki/pub?start=false&amp;loop=false&amp;delayms=3000
895 https://not

2024-07-15 13:52:12,717 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


988 https://etherwallet.mobilelab.vn/
989 https://mais78.wixsite.com/my-site
990 https://bafybeig5xehg7kytdz2ywgrxhm3owi4w4hjhv2hhpppxmr7e3arxwt74f4.ipfs.dweb.link/
991 https://cj95635.tw1.ru/DGT/in.php
992 https://sites.google.com/view/cxcfre/home
993 https://lpoirew.firebaseapp.com/
994 https://oihkj.gcq5gk291x5547.workers.dev/
995 https://corndirect.in/cd/Vorgang
996 https://home-102904.weeblysite.com/
997 https://pub-2c41dc2a4fe544379dd65a62b31c94b1.r2.dev/index.html
998 https://docs.google.com/presentation/d/e/2PACX-1vSHOZiYDpg1Xl3XPLlpZzEog5PT-ghf-Na3uTwbVnHTa4NPRMyJpnAqgnAWWkz9nuRnc18RzWzdvjMp/pub?start=false&amp;loop=false&amp;delayms=3000
999 https://support-pages2024.start.page/
1000 https://decentralizedex.pages.dev/app/
1001 https://cloudflare-ipfs.com/ipfs/QmayZEVDFyqfUa49XUogVc6q2Ge9S7V9rQJFaRoMtj7uQh/?sid=ehhveko&eui=
1002 https://www.idschweizconfirm.sviluppo.host/df/pass.php
1003 https://new.express.adobe.com/webpage/yjAhebpZIk5qW
1004 https://lookerstudio.google.com/r

2024-07-15 13:59:03,134 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


1238 http://anasathalassas.gr/modules/mod_simplefileuploadv1.3/elements/fold/ionoscom/index.html
1239 http://etracking-cttpt.com/
1240 https://mari-etta98.systeme.io/chaty/urtre
1241 https://pub-8f636a7478da4c87951f6072a7a6f29f.r2.dev/link.html
1242 http://vtfeu.pages.dev
1243 https://pub-200e4f2bad7546ae9bd0d1e062a73f0f.r2.dev/index.html
1244 https://docs.google.com/presentation/d/e/2PACX-1vQFDamXCkXUWqkDXTDvV2Q0DhB-jIqiF-XLXxAIEiEK2_Qi6-KSO8G58HRq5ttOMl6rUhVwVcXrBby4/pub?start=false&amp;loop=false&amp;delayms=3000
1245 https://smanbvhgdyr352.wpenginepowered.com/wp-admin/network/39937U/92G21.htm
1246 https://www.bugouzhu.com/smywbc641yr1da9c88
1247 https://docs.google.com/presentation/d/e/2PACX-1vQ1wt2qvmvQUz1gnl_5f4z47emMC6ygFqBOBPHxJ9hc__6BA7q4du2350PT6WEBzhp5kJ--5XW6QaR4/pub?start=true&amp;loop=true&amp;delayms=3000
1248 https://securesunflowerbank.weebly.com/
1249 https://phanteokwalett.gitbook.io/us
1250 https://docs.google.com/presentation/d/e/2PACX-1vR0IGh7WDgc92mzvGXRhjXm81I8h

2024-07-15 14:51:22,046 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


3122 https://nhanquafreefiree.grarena.vn/
3123 https://login-htomail.webcindario.com/
3124 https://s-idcenter.net/?uuid=a6762574-5f16-460b-b471-ca636847f322
3125 https://docs.google.com/presentation/d/e/2PACX-1vRgWEDOvXaO8OTnTp2sIU7o8NoQyG8RSZESDGax40YD_THxwOs180cpy_MQyL3Rn5_muAoT_Jtn23dc/pub?start=false&amp;loop=false&amp;delayms=3000
3126 https://pub-5c0aa65f5f224858a03e429b595c1811.r2.dev/dropbox-sign-in.html
3127 https://hotm.art/B7zlwVm
3128 https://microsoft-102779.weeblysite.com/
3129 https://btinternet-108088.weeblysite.com/
3130 https://ionian-woolen-bush.glitch.me/public/id56me00jt.htm
3131 https://krkenlogis.gitbook.io/usa
3132 https://janhi.vercel.app/?1195b079-4ec1-4530-84c4-323306962480
3133 https://almardoof.com/Webmail/3/Webmail/webmail.php
3134 https://docs.google.com/presentation/d/e/2PACX-1vQZkZ0eEhuYyJh48kuoTlg_gcdak8xsthZ4ezvqVEltaXZb2GQRA_iz0U0t2IYB4VbR_XFzeLnlpvG9/pub?start=false&amp;loop=false&amp;delayms=3000
3135 https://pub-a81aa4bbf83846b8a892985d5bbc3a6f.r2

2024-07-15 14:52:58,548 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


3178 http://dl.mod30t.ir/amin/templates/rar/perl/linkedins.cn/
3179 https://sportybetbadder-009.weebly.com/
3180 https://aol-100899.weeblysite.com/
3181 https://hamburg-dfb7be.webflow.io/
3182 https://bov-verify.firebaseapp.com/
3183 https://pub-201a3d110f174755906cf96bab68a139.r2.dev/wine.html
3184 https://server-100645.square.site/
3185 https://pub-2e86082d752843969e1c4572009c2ad7.r2.dev/alert.html
3186 http://newburycafe.co.za/Webmail/67/Webmail/webmail.php
3187 https://pub-96d6173afb8f47068d23236d3491a584.r2.dev/index.html
3188 https://interiapl-104828.weeblysite.com/
3189 https://hpr.ths.mybluehost.me/wp-admin/it/
3190 https://conta-cgd.com/web/PTPW1/tpl.asp?si=
3191 https://forms.office.com/pages/responsepage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__m3snZBUOU9KUUQ0RlFJVFVBWjYzQVFYUkpEUEYwMS4u
3192 https://viewclosingdocument1.weebly.com/
3193 https://amandathornle.wixsite.com/my-site-1
3194 https://netflx.pages.dev/
3195 https://skgpyhyrkpsn.com/
3196 https://validar-aqui-ya.

2024-07-15 14:53:23,516 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


3199 http://q-r.to/bf5b00?bradesco.com.br
3200 https://sz0lr48.duckdns.org
3201 https://www.flowcode.com/page/margidn
3202 https://solucoes-rener-fatura.blogspot.com/
3203 https://form.123formbuilder.com/6613699/brunobackgroundcheck
3204 http://sm-zgoda3.pl/wp-includes/xiamei/neteasehardest/900/index.php
3205 https://docs.google.com/presentation/d/e/2PACX-1vSH8XafFxQ7E8x29We7HGFOD4_pewKE5CUpqatsAGi7HGhRGvrwHxoco-OcLBRBVXFzgOzkb_HEvpFa/pub?start=false&amp;loop=false&amp;delayms=3000
3206 https://th797a7f9asfasfasfasfas88787as8f7a8sf7afa.pages.dev/
3207 https://docs.google.com/forms/d/e/1FAIpQLSf5DB470PluBLAc9fKJ_hq_AK8VmWWOYfwGjWtsW9NEbx6ntg/viewform
3208 https://att-102715-106694.weeblysite.com/
3209 https://www.ozgurprekast.com
3210 https://docs.google.com/presentation/d/e/2PACX-1vTZDeFnrYkWEqM7WCZyqg5zdxzRylW0QdUiEcGjP0mjKhfoimV_Z5XPL51gVPjvbm0Zm1S_37WOKyPS/pub?start=false&amp;loop=false&amp;delayms=3000
3211 https://yoydzs.blogspot.com/
3212 https://bafybeieqtipwnhknas3brkuc24aefrgi

2024-07-15 14:57:57,854 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


3354 http://q-r.to/bech8x
3355 http://tesioewurdhjsieyytdodma1.pages.dev
3356 https://eng.ujd.mybluehost.me/D/dhl/dhl/dhl/home.php?newtoken=
3357 https://support-apply-contact-us.surge.sh/
3358 https://bell-102086.square.site/
3359 https://cloudflare-ipfs.com/ipfs/bafybeihygy4mshyzxazm533gg2wjuiu2ijcmtdff7hxcu4ycmiwwruqaua/dsxctgyhvh.html
3360 https://pub-12c79d09670f4464af9de32e4799a256.r2.dev/12345.html
3361 https://nyz.ujd.mybluehost.me/wp-admin/exp/auth/index.php
3362 https://www.flowcode.com/page/attupdatemail89
3363 https://wkq77k.webwave.dev/
3364 https://telstra-104094.weeblysite.com/
3365 http://globalmedictoursin3rdworld.advancedplasticsurgery.com.au/?email=YmxhQGJsYS5jb20K
3366 https://de10027.web.app/
3367 https://bafkreid3534ipuaj7wirl2o7fb4e4hhjza6zjngdwiyomtda6mmrrlr4lu.ipfs.cf-ipfs.com
3368 https://docs.google.com/presentation/d/e/2PACX-1vQpyqyY9tmxmhadryNDHaNLGWhxe_wIg_Vttvr6rK_3jGJO_Wh6sCiog-CsTpP5Rl9noIKElALLTtnO/pub?start=false&amp;loop=false&amp;delayms=3000
3369 h

2024-07-15 15:05:00,544 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


3604 https://telegra.ph/KF-679808-11-27#
3605 https://bafybeif66f3rjo7qq6w3ccrgvn5cbmyze7korokglhyydwq443smbabfqi.ipfs.thirdwebipfs.com/homefront.html
3606 https://pub-423cb9acafc54971814c16ae6b773f6f.r2.dev/index.html
3607 https://pub-8450d7d7fe834a41895f637fd53a8438.r2.dev/mac7.html
3608 https://docs.google.com/drawings/d/1iq46bvQnCHGbfjXzRlDKD9TQ4UjDEQKo_X30CfDMqcA
3609 https://micsft.pages.dev/
3610 https://nftstorage.link/ipfs/QmWRogyS5u9SAqyZ71wf5zDMPFnp5Kjf9KWzdwnMXTFqgn/enclosed.html
3611 https://8mrssxhzo.duckdns.org
3612 http://lawcliq-1318439371.cos.ap-tokyo.myqcloud.com/lawcliq.html
3613 https://docs.google.com/presentation/d/e/2PACX-1vQHTofu8CRK-Qd50_JhQYpR6Q2B1gjgYjyhqqHI2uyz5A8bwdIfED6wN05P8fvLCizuZC1buSfJeuFW/pub?start=true&amp;loop=true&amp;delayms=3000
3614 https://autoiothiatowers.web.app/
3615 https://telegracm.org/a/
3616 https://telstra-106488.weeblysite.com/
3617 http://rustblock.pages.dev
3618 https://ipfs.io/ipfs/QmT7eHFTEuxYZPQrZRLUdcrMMCoutAU97ZeQqvoPH6kW5H
3

2024-07-15 15:10:50,393 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


3785 https://pub-e5748588f20f4fcc9a07ee3482f44c67.r2.dev/59e1b1a120e40bf6e388a325ccb3c1a8.html
3786 https://cloudflare-ipfs.com/ipfs/bafybeibs74vpjir5gvowcq3o5spl74az2twh2eczslhowwbwgbjt5bbwle/pxps6thauth.html?aire.rihe@envir.ee+
3787 https://b5khp4.webwave.dev/
3788 https://helpmettacase1000.web.app/
3789 https://gdhdjddjdss.weebly.com/
3790 https://mail-live.net-s03.net/rf/?code=60d44fedf11f408a2fcbe7553ebc6130
3791 https://docs.google.com/drawings/d/1ieI8z2sl9U_6FwG_CYHm2UJmTIhpvl4R11dwxLEWbS8/edit
3792 https://les6886.wixsite.com/my-site-1
3793 https://pub-730aa62ec38e42d3a2dcee0382a8a9dc.r2.dev/update/index.html?cms=
3794 https://docs.google.com/presentation/d/e/2PACX-1vT7X_HvnVptbsdRaljGU1qM7fdTbyS2wpoZpjDbUNFsuJCIyBxMiV1bdm59NzhKSPqVboJe57i7UCdl/pub?start=false&amp;loop=false&amp;delayms=3000
3795 https://bafybeieb4jzitoshsombplqtbqvebsds45iven7gopm7motrmqjsbxh3za.ipfs.cf-ipfs.com/%E6%B3%A8%E5%86%8C.html
3796 https://attandtserviceupgradesnow.weebly.com/
3797 https://t.co/o1kFT7

2024-07-15 15:18:53,532 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


4075 https://tyny.to/s39c08
4076 https://ipfs.eth.aragon.network/ipfs/bafybeihox2fy2wit33cvzvxal3xw7nw7lnyr3s4dnffzlvqjyxpobisnxm
4077 https://orangeassitanceinf.wixsite.com/my-site
4078 https://rb.gy/1h8m44
4079 https://nfj2.pages.dev
4080 https://sites.google.com/view/dromaxficwe/accueil
4081 https://sites.google.com/view/olaiehdfgb/home
4082 https://pub-b65e785cf58b426da1b4071ab8a566e9.r2.dev/CHAMEL.html
4083 https://connecenwallet.gitbook.io/us
4084 https://pub-f1d8d2c90a5d498f8b8a266263350e6f.r2.dev/link.html
4085 https://odesli.co/j8hfzdsk6cc5w
4086 https://docs.google.com/presentation/d/e/2PACX-1vSsYwJ9fgqcd0XMjnGR82TKNEWJiq3oLazorQV4e2UjTH9sK_0KCpFvHaEw5sWauKH2eWE1HjFnfetJ/pub?start=false&loop=false&delayms=3000&slide=id.p
4087 https://docs.google.com/presentation/d/e/2PACX-1vQmTStPXpkR5i90m4fjajXStUKWDHmL1BWVHkdMmJQvY2znwmIoMqf_JorSdj0HZjl2lv-nu0YvNSsv/pub?start=false&loop=false&delayms=3000
4088 https://allegrolok.rezerwacja-1937571945.com/s/00TEU
4089 https://je5kk.weebly.co

2024-07-15 15:19:31,575 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


4100 https://inmaculada.edu.ec/
4101 https://docs.google.com/drawings/d/1M6Nj1eK8sqbDuhwSvgeyJMMbfH0ACh1V3mUgRS26db0
4102 https://juno-100313.weeblysite.com/
4103 https://www.pagamenti-aruba-it.com/
4104 https://pub-e346a5ab36d944a3b44a7d615f335c4d.r2.dev/member.html
4105 https://ms3vww.mushroomsmokeshop.com/?q=3DR0JlYXVkaW5AcmhyaW50ZXJuYXRpb25hbC5jb20=3D
4106 https://fixdefinetwork.pages.dev/
4107 https://docs.google.com/drawings/d/1V1HMmuiY3L1vSRkn2FboziAW5jHVOag6DUCei4UaJKM/edit
4108 https://docs.google.com/presentation/d/e/2PACX-1vQM9thsaMNcp12DI5T3mnaCHFtdVBYw_v2NTObqx88oqOakRF-ik8xxIkL0GiP1pIh-pp5DlEfeRlMW/pub?start=false&amp;loop=false&amp;delayms=3000
4109 http://scntxx0qm.duckdns.org
4110 https://mute-lake-3308.t38uuz0b.workers.dev/
4111 https://docs.google.com/drawings/d/1ROG-CqS7sTV0U31kfdLUXELAjoHW95UK25IVzs5CuQQ/edit
4112 https://docs.google.com/drawings/d/19CXUUOcOcodNVn35OrBvR3K3U56TH-h2d74KYwnCw4M/edit
4113 https://grupopetro.com.ar/en/?https://clicks.richersoundsvip.co

2024-07-15 15:33:03,411 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


4521 https://roblox.com.zm/groups/8881254866/
4522 https://ziraatbankasi.pages.dev/
4523 https://epicmininggroups.online/?shiny
4524 https://cdecommerce.com/client/login
4525 https://www.0432uuu.com:8989/
4526 https://needactcorporation.com/
4527 https://nxh.atazanavir.org/
4528 https://www.redwings-france.fr/collections/bottes-bottes-imperm%C3%A3%C2%A9ables-c-1_8.html?sorting=pricedesc
4529 https://ent-klingshirnmadeline.pages.dev/help/contact/671597213548590
4530 https://aidatislmer.online/login_up.php
4531 https://hairlessskin-ingolstadt.de/
4532 https://flux.ssdigitalsmm.com/
4533 https://icscards-beveiligen.pro/
4534 https://www.bet83008.com/
4535 http://ee575365.vip/
4536 https://grrru9.z30.web.core.windows.net/werrx01USAHTML/?bcda=1-855-498-3299
4537 https://1425225880.xyz/akbank/
4538 https://0915-asiakaspalvelu-op.info/
4539 https://bafybeifotd3zteubedkrscvoj7ifq67dwbx5qrc3zyyktiq5k4dyojtmbm.ipfs.dweb.link//
4540 https://chseyu.duckdns.org/
4541 https://22crown888.com/?c=siena

2024-07-15 15:35:44,080 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


4619 https://santanderreencuentra.es/
4620 https://teslacrypto-promo.net/
4621 https://vibolt.site/
4622 https://laixiongti.pages.dev/?silap=toto12
4623 https://packageshipmentinfo.com/app/index.php?view=index&id=19c6a97bf35ed5c281dff533de407ec6
4624 https://script4.webcrackdigitals.com/
4625 https://pub-54c2803521d24db38d36a28389523c49.r2.dev/index.html
4626 https://abhigyan2212.github.io/ReCreation-of-Netflix/
4627 https://aanbhientertainment.com/
4628 https://conveyancingportal.com/NewWebsite/EROT/ReportOnTitle/Index
4629 https://edevlet-giris-ceptesube-tr.app/
4630 https://cf.hk.1111r.icu/
4631 https://att-mail-102563.weeblysite.com/
4632 https://36508.xyz/
4633 https://pub-75a5f4aa70c34156a65ab11f6988b245.r2.dev/mount.html
4634 https://kopyjct4.pages.dev/
4635 https://thum.polekel.biz.ua/kasir/?slot=toto12%20link%20alternatif
4636 https://tevahrvatskaoutlet.com/
4637 https://www.hitecshoesireland.com/
4638 https://yde.atazanavir.org/
4639 https://santander.cf.sandbox.motrada.ch/
4

2024-07-15 15:40:39,130 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4745 https://vongquayfreefire.free-fire.io.vn/
4746 https://jobvertex.net/
4747 https://atikflor.online/
4748 https://zcl.atazanavir.org/
4749 https://nwtmedia.ca/app/track.php?userid=9670b72ac07a0e5bc5a0725bf1fc5909&ue=67008bcf4f584d222612107b64e80e8c
4750 https://messagerie-sg.dzpwroc.pl/vro/ktr/PNZ/
4751 https://rubyshophei.com/
4752 https://www.bet83008.com/
4753 https://www.goyard-saudiarabia.com/
4754 https://e-d-evlet-iad-e.shop/
4755 https://bafybeibozqrr32p7z2f3pwdq3h6o4co45eyk5q5mr6d4oozw77ey4uv6vi.ipfs.dweb.link/
4756 https://www.freemaxperu.com/marvos-c-19_29/d666354-freemax-marvos-vaina-dtl-transparente-freemax-vape-per%c3%a3%c2%a3%c3%a2%c2%a3%c3%a3%c2%a2%c3%a2%c2%a3%c3%a3%c2%a3%c3%a2%c2%a2%c3%a3%c2%a2%c3%a2%c2%ba-p-302.html
4757 https://netflixclonebykislayy.vercel.app/
4758 https://www.hirai-gifu.com/
4759 https://rafusacada.com/?u=bqkpd0x&o=xtc0tv6&m=1
4760 https://iade-temmuz.sbs/
4761 https://boozersadda.com/
4762 https://mail.my.ups.trackingdelivery.209-38-30-79.cpra

2024-07-15 15:43:36,265 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


4821 https://roblox.com.zm/users/1467428575/profile
4822 https://mutates-dodecyl-c444be9cd9-967ee6578-c014858e8-4981098c1.pages.dev/f6e7f9de5c12900ae3a6044/958ea5ffafc84ee486a54b44c/?tqjczban=0c6d016a5d18f8ccd14479bb
4823 https://fanyv88.com/https/www.mom.gov.sg/newsroom/press-releases/2022/0325-government-accepts-recommendations-by-the-tuas-explosion-inquiry-committee
4824 https://nyglxy.com/
4825 https://hlt.atazanavir.org/
4826 https://sicoobnet.digital/
4827 https://yeed3-secondary.z30.web.core.windows.net/werrx01USAHTML/index.html?bcda=(0101)-50360-84553
4828 https://www.randmvapebrasil.com/
4829 https://www.on-shoescanada.ca/
4830 https://f1bnk.online/
4831 https://jz0ffcxgkg1olcjog.pages.dev/smart89/
4832 https://2024isbank-0faizkredislemler2.xyz/isGun/giris.php
4833 https://achievementapexx.com/
4834 https://x-play.pubgxbest.com/cgi-sys/defaultwebpage.cgi
4835 https://fanyv88.com/https/www.mom.gov.sg/terms-of-use
4836 https://www.uggsbootspolska.com/
4837 https://dcmpx.remotevs

2024-07-15 15:49:49,773 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


4959 http://www.instagram.co.az/index.html
4960 https://i6c696e65o6d65z.oszar.com/en/
4961 https://meet-my-love.top/?u=fy082k7&o=mb2kpbt&t=adventurelandgallery.info
4962 https://aanbhientertainment.com/
4963 https://metamsskigen.gitbook.io/us
4964 https://dschgsdvgh2356rt23.pages.dev/
4965 https://teslacrypto-promo.info/
4966 https://huntingthoclientsdash-login-huntingon.chaecysme.com/
4967 https://sg-sce1.icu/1/
4968 https://vbucks7.com/
4969 https://ipfs.io/ipfs/bafkreidubvxog4n3tr7n3upde7vxhe3dgbsiytcu3qw2bzktouekcdodfq
4970 https://0830.melonaf839.workers.dev/
4971 https://suomiturva.info/public/pages
4972 https://hotel-id8587629.com/sign-in
4973 https://www.embedista.com/j/instagramfeed.js?pnp=1720707976196
4974 https://business.contactverycenter.com/case/118370644911237
4975 https://voddths.com/home/index.php
4976 https://suspended-website.com/m/
4977 https://www.dvlmoo.com/
4978 https://wearingtoday.com/?u=bqkpd0x&o=xtc0tv6&m=1
4979 https://profielts.com/basket168-slot-login-18/

2024-07-15 15:52:04,910 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it


5007 https://roblox.com.zm/groups/1183620654/
5008 https://messagerie-sg.dzpwroc.pl/vro/ktr/PNZ/
5009 https://www.consummateservices.com/public/9QdKkiKc6mfYXQznLYxh0nNZiRiuMnmo
5010 https://dcmpx.remotevs.com/jp/ne/docomo/smt/cfg/SL/auth/cgi/%20dcmpx.remotevs.com%22,%22155.248.176.223
5011 https://www.whatsapp-wn.cyou/ch.html?lang=ch
5012 https://www.dhlecommerce.be/en/gogreen
5013 https://claim-decimalchain.com/
5014 https://xtreme-funds.ltd/
5015 https://broadviiews.world/
5016 https://napsify.com/Facture/
5017 https://www.vipcongres.nl/
5018 https://cdecommerce.com/client/login
5019 https://dupont-community-credit-union.sitey.me/
5020 https://verizon-5g-landing-page.dev.cdwv.pl/
5021 https://posttrackdashboard.top/
5022 https://hjfurtt.icu/qa/
5023 https://andaground.com/pola-pandora188-3
5024 https://iade-temmuz.sbs/
5025 https://gsjs.pages.dev/
5026 https://0915-asiakaspalvelu-op.info/
5027 https://x.qeint.apple.barclaycardrewardsboost.com.eng.cartera.com/
5028 https://access.line

2024-07-15 15:55:08,529 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5089 https://konferencija2023.e-commerce.ba/
5090 https://hsbcbank.000.pe/?i=3
5091 https://gap.atazanavir.org/
5092 https://metamacisklogin.webflow.io/
5093 https://pfnt.fectorid.com/fyzzfdgagrodmarglgrdux866741437087543494hpccwoenhtznjcbnfohoglv?dyhfaiaarypczuicthuqm7698909077845912981208618esqqnxmmadygtrqzxd
5094 https://www.tpmsuruguay.com/
5095 https://yenib508.top/login.php?bank=18
5096 https://sg-sce1.icu/1/
5097 https://xtwda.com/
5098 https://juhyt4.pages.dev/
5099 https://stanbicbank.affluent.africa/private/1420/
5100 https://pub-e240f325746b4252b3302dccb255d042.r2.dev/bea21.html
5101 https://ipfs.io/ipfs/bafkreidubvxog4n3tr7n3upde7vxhe3dgbsiytcu3qw2bzktouekcdodfq
5102 https://ipfs.io/ipfs/bafkreidubvxog4n3tr7n3upde7vxhe3dgbsiytcu3qw2bzktouekcdodfq
5103 https://cf.gundamf6.workers.dev/
5104 https://ipfs.io/ipfs/QmWbMm4XqCG4T6VMtKKh4eH9TEa3eKYL9T44Lk14S7z4wZ
5105 https://pub-54c2803521d24db38d36a28389523c49.r2.dev/index.html
5106 https://pub-3509f1589d6e4624a7c663fb2bb8e192.r2

2024-07-15 15:58:38,911 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5181 https://konferencija2023.e-commerce.ba/
5182 https://usrx.lnfqnwgl.top/favicon.ico
5183 https://linealayerbank.pages.dev/
5184 https://www.citicorretora2.com.br/home.php
5185 https://thum.polekel.biz.ua/kasir/?slot=toto12%20link%20alternatif
5186 https://auth.member-upgrade-ourtime.workers.dev/favicon.ico
5187 https://sgps-user.icu/1/
5188 https://pancakeswap-alphav3.vercel.app/
5189 https://sites.xd.mk/
5190 https://awards-aeth.org/
5191 https://aurameetlove.life/?u=5q8kd0x&o=gt7p8zw
5192 https://dev-salmanislove.pantheonsite.io/swiss/CHFINAL/be65e/
5193 https://bafybeifotd3zteubedkrscvoj7ifq67dwbx5qrc3zyyktiq5k4dyojtmbm.ipfs.dweb.link//
5194 https://digitalbrevkassemitd.com/
5195 https://official4.secureleads.cloud/
5196 https://tbwaba.com/index/index/trade/tradelist/trade/tradelist/trade/tradelist/trade/tradelist/trade/tradelist/trade/tradelist/trade/tradelist/trade/tradelist/trade/tradelist
5197 https://pub-0c062afe82544962aee957f640f2ca2d.r2.dev/index.html
5198 https://servic

2024-07-15 16:02:26,755 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5275 https://www.roblox.com.lk/users/2815788120/profile
5276 https://www.9955304.top:8989/
5277 https://rebellionrose.pages.dev/
5278 https://messagerie-sg.dzpwroc.pl/vro/ktr/PNZ/
5279 https://ndw5xvotehflt.pages.dev/smart89/
5280 https://support-request.pages.dev/
5281 https://meatamacktlogn.gitbook.io/us
5282 https://www.discoveryintb.com/
5283 https://ycf.atazanavir.org/
5284 https://yj765srwfeq.club/
5285 https://hsbcbank.000.pe/Security.php?i=3
5286 https://www.bedrocksandalsfrance.fr/
5287 https://sgps-usersc.icu/1/
5288 https://haveplentymusic.com/
5289 https://facebook.shengjinshu.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F
5290 https://app--trzoor.webflow.io/
5291 https://windowssystem-essentials-online.pages.dev/
5292 https://indranilpaul15.github.io/netflix-clone/
5293 https://pagedoc65.pages.dev/?8d2a32bc00cd51abe4438aa220e9a4f0lyl3q6o5=U2FsdGVkX1%2BRT98SdlNSouoCmCYCtys4jhyBKUhBlgtIhORGR8S7DFKjl%2BElmqMiNq26czROH4eR4x3q0toVvArCR2moWXIytiWIsvXUSP6IaPEgfruoLGZiiRCJKW0vq

2024-07-15 16:03:03,844 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5294 https://www.lowagreece.com.gr/lowa-tibet-superwarm-gtx-%ce%9f%cf%81%ce%b5%ce%b9%ce%b2%ce%b1%cf%84%ce%b9%ce%ba%ce%b1-%ce%9c%cf%80%ce%bf%cf%84%ce%b1%ce%ba%ce%b9%ce%b1-%ce%93%cf%85%ce%bd%ce%b1%ce%b9%ce%ba%ce%b5%ce%b9%ce%b1-%ce%9c%ce%b1%cf%85%cf%81%ce%b1-%ce%93%ce%ba%cf%81%ce%b9-greece-04216legu-p-179.html
5295 https://telexsexy.vercel.app/
5296 https://jackwolfskinmexico.com.mx/ropa-tshirt-c-1_31_33.html
5297 https://elaineredlick.com/sigin/language.php?32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e32506f9e0e54fffcbca23e7661896e6e
5298 https://meet-my-love.top/?u=fy082k7&o=mb2kpbt&t=adventurelandgallery.info
5299 https://mortezaconfig.mortezaakbaridp.workers.dev/
5300 https://www.b45009.com/
5301 https://ipfs.io/ip

2024-07-15 16:05:04,298 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5327 https://sinhnhatfreefire7tuoi.gaerana.io.vn/
5328 https://teslax22pl.web.app/
5329 https://ekwsopldendjfg.weebly.com/
5330 https://saledelivery.zone/?cp=fmlcqhob
5331 https://aaexcoin.shop/Trade/tradelist
5332 https://appvalidations.pages.dev/
5333 https://nobullfrance.fr/
5334 https://pub-637d30dbff0f440fa3398853dc159a6f.r2.dev/clange8c9dfdf99saed.html?email=*@
5335 https://instagramcan.blogspot.com/
5336 https://unep.quantalys.com/
5337 https://mohitvar007.github.io/home_page_net/
5338 https://sharedfile8.pages.dev/?335323cf467957678d75db3105c84af5lykrbcbb=U2FsdGVkX19vMDdy4PEfR0Gp5%2FErZyfTGixEo%2FaXUgUQP5nTnVb8hQDnLLuQrK89qdsiVTHaUTAw6gJ8tGypZHqeu%2Fil7DRLqw1xClqJyxtm8gtBSh4Cg%2BqsrxULS9jbiWp7wO6obclXrTNjVMULyByZS3t4Emj5FepFoT8SbpxjeW%2BJQZsFHLAXxkLwUbHw3FV36BJG%2BQaJJC%2Fkcvo9%2BxcN7yBR%2BYSpejEhMwVy%2FT2DixJ%2Bnt%2BMbWh52FQTgN4Ya9KLe5RpVWFAoCFX5uxWVTf7K6aPkn1UdCxQC0PZZxvAnWySh2IReRdFxKll%2BaEICKK9o2qnTvDlxY5asdYG%2BP%2BlZrOU7gSwTORloqO2OptikHtyc9wAeuQ%2FGxRrMPoG38YUsScF7%2FQG

2024-07-15 16:15:08,203 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5616 https://cautran.id.vn/akbank/?fbclid=PAZXh0bgNhZW0CMTEAAaYgN8YYpzTqOj2azu3SjhBZ07ZDg95VboeEVgEagU56tsncFvsD-LsBow0_aem_UGzBDRYsoneGu9hD2OYD_g
5617 https://www.geoxbulgaria.com/index.php?main_page=time_out
5618 https://aidatislmer.online/login_up.php
5619 https://agamak.eu/
5620 https://pub-06e80814dbe14a36a449e659d43bfeee.r2.dev/doc_start.html
5621 https://5fgfgffg4g4gh4f.blogspot.com/
5622 https://allecars.com/sigin/language.php?d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515d228a01ab21a93305e8320ddeccb9515
5623 https://www.nikeoutletsverige.com/
5624 https://ginutbka.com/
5625 https://www.b45009.com/
5626 https://pancakeswap-sigma1.vercel.app/
5627 http://teleqram.work/web
5628 https://lkc.atazanavir.org/
5629 

2024-07-15 16:22:45,775 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5792 https://roblox.com.py/users/2432865676/profile
5793 https://tccbmkartiadeleritr2.b-cdn.net/
5794 https://merrell-clearance.com/
5795 https://y0ur0ffice-65.docusgn-sharedviaoffic3.workers.dev/jsdisabled/
5796 https://fanyv88.com/https/www.mom.gov.sg/terms-of-use
5797 https://fb-policy-violation.pages.dev/
5798 https://www.xuyvdj.com/
5799 https://pub-3509f1589d6e4624a7c663fb2bb8e192.r2.dev/kevogrencievlerisultan69.html
5800 https://bafybeihxpdl65aea3spuyoo6ye4w2i2li3vezwevuoerbbttqeduwjqnsq.ipfs.cf-ipfs.com/
5801 https://www.conveyancingportal.com/NewWebsite/EROT/ReportOnTitle/Index
5802 https://17c365.com/
5803 https://thegoldenratioprojects.in/momeweb/Privacy-statement.html
5804 https://www.geoxbulgaria.com/%d0%bc%d1%8a%d0%b6%d0%b5-c-20/?sort=20a&page=4
5805 https://santanderexperiences.es/
5806 https://moitramasklogin.gitbook.io/us
5807 https://www.vipcongres.nl/
5808 https://bet938g.com/
5809 https://pub-9a7a1ac0cceb48798a1c5f8544500ca8.r2.dev/index.html?user-agent=mozilla/5.0+

2024-07-15 16:24:17,970 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out


5841 https://www.intimissimi-portugal.pt/
5842 https://unep.quantalys.com/
5843 https://affluent.africa/private/1420/
5844 https://www.alo-yoga-mexico.com.mx/
5845 https://mine-liness.top/
5846 https://grnnthzzlcbsvrrlnd.com/
5847 https://web-telegram.ru/
5848 http://amplerequire.top/bx4ng7rcoxggna6/g1y0p8nnyk2/ghe35kh63f35h6h4/
5849 https://pub-32a1bac6a31e4ac59b23f823ce1629e3.r2.dev/index.html
5850 https://villa-karkos-mykonos.com/
5851 https://messagerie-sg.dzpwroc.pl/vro/ktr/PNZ/
5852 https://hairlessskin-augsburg.de/
5853 https://realtylab.com/?u=bqkpd0x&o=xtc0tv6&m=1
5854 https://tqj.atazanavir.org/
5855 https://agamak.eu/
5856 https://ipfs.eth.aragon.network/ipfs/bafybeiflj5denlouw5sg7ahz4d27vbsvxfjjjb7ymz7c47jmmcmisxj3cq/
5857 https://0912-asiakaspalvelu-op.info/
5858 https://pttgov-cn.top/help/
5859 https://hemenhallederiz.click/
5860 https://citloginnow.gezuxuru.workers.dev/
5861 https://yeed9-secondary.z35.web.core.windows.net/windows/index.html?bcda=(0101)-50959-02152
5862 

2024-07-15 16:25:32,147 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5873 https://cautran.id.vn/akbank/?fbclid=PAZXh0bgNhZW0CMTEAAaYgN8YYpzTqOj2azu3SjhBZ07ZDg95VboeEVgEagU56tsncFvsD-LsBow0_aem_UGzBDRYsoneGu9hD2OYD_g
5874 https://wc-node.pages.dev/
5875 https://www.igetkuwait.com/iget-5500-%c3%a3%c2%b9%c3%a2%c2%86%c3%a3%c2%b9%c3%a2%c2%81%c3%a3%c2%b8%c3%a2%c2%ab-c-1_36
5876 https://currentktt.weeblysite.com/
5877 https://rsidmegovus.publicvm.com/id.me/id/secure/online/profile.html
5878 https://akminings500.com/?shiny/
5879 https://defi-uniswap-protocol.netlify.app/
5880 https://telegram18sex-naughty.pages.dev/
5881 https://marketbids-offers.com/
5882 https://60661.xyz/
5883 https://prathameshndixit.github.io/netflix/
5884 https://ava.game.naver.com.krorcl.reinzvpn.my.id/
5885 https://dcmpx.remotevs.com/jp/ne/docomo/smt/cfg/SL/auth/cgi/
5886 https://acubancorp.com/
5887 https://60723.xyz/
5888 https://support-request.pages.dev/
5889 https://nifrole.icu/qa/
5890 https://www.995531aa.com:8989/
5891 https://steamcommunity.asia/
5892 https://giod1n.web.app/0.3

2024-07-15 16:26:40,990 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5906 https://konferencija2023.e-commerce.ba/
5907 https://trade.santanderusedcars.com/
5908 https://seeproc.com.br/test.txt
5909 https://mitmsklogiuma.gitbook.io/us
5910 https://saidtlarrr.net/
5911 https://miusiabc.vip/
5912 https://fdr5ete.pages.dev/robots.txt
5913 http://www.telegrnal.club/
5914 https://agamak.eu/
5915 https://sycinue-rdc.github.io/ITS-Dashboard/
5916 https://ffkelwssnehdsjd.weebly.com/
5917 https://affluent.africa/private/1420/
5918 https://microsoft-secure-alert-8irlc.ondigitalocean.app/?phone=+1-877-200-9638
5919 https://www.oncloudmonsterturkiye.com/
5920 https://www.digicomp.ch/
5921 https://yenib507.top/?e_devlet=1&utm_medium
5922 https://pub-08315c997de948f2a26541af5e3120f3.r2.dev/auth1.html
5923 https://hokaskooutletsalg.com/hoka-one-one-herre-performance-kort-erm-tops-imperial-bl%C3%A3%C2%A3%C3%A2%C2%A3%C3%A3%C2%A2%C3%A2%C2%A5-norge41kan-p-59.html
5924 https://ps-sguser.icu/1/
5925 https://ccc.hmoob123.workers.dev/
5926 https://yy-liness.xyz/
5927 https://a

2024-07-15 16:27:30,816 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5931 https://konferencija2023.e-commerce.ba/
5932 https://rwg.atazanavir.org/
5933 https://one-digitalservice.ch/login/login?Location=https://one-digitalservice.ch//
5934 https://pub-01d9210ef25e430e90d68cfaf7c9b3be.r2.dev/allroundmen.html?email=t***.s*****@l*****.si
5935 https://pemulihan.akun.dana.webappsystem.com/
5936 https://pub-46ec560551b44f6387ad30dd36f4f128.r2.dev/index.html
5937 https://login.mijnsnapchat.com.accountsettings.app/
5938 https://ios.yahoks.com/
5939 https://www.truereligionoutlet.de/collections/m%c3%a3%c2%a4dchen-jeans-kinder-c-57_58.html?z2vuzgvyptm=
5940 https://www.bet83008.com/
5941 https://mit-borgereboks.com/
5942 https://sowmyasreeravuru.github.io/Project1/
5943 https://pub-02dd55f48a9541ac81a1e7570171f4c4.r2.dev/ebyy.html
5944 https://techincludes.click/
5945 https://www.kontomaniak.pl/
5946 https://thegoldenratioprojects.in/momeweb/Legislation.html
5947 https://uitmuntendshop.nl/login
5948 https://telstra-107806.weeblysite.com/
5949 https://tg3.pages.de

2024-07-15 16:29:41,474 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed


5980 https://konferencija2023.e-commerce.ba/
5981 https://lupisan.com/sigin/language.php?0a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e2340a717109c37f32dd0c0b802e7709e234
5982 https://www.dcshoelisboa.com/collections/sapatos-tenis-skate-c-1_3.html?&gender=1
5983 https://kehidupantuanmuda.com/?join=KOITOTO
5984 https://fnal-tiktokshop-rusd.vip/
5985 https://ipfs.eth.aragon.network/ipfs/bafybeifkh27c2b2hqmm2tte5jp6eq3uincyhmxxaukoespre46zjpexybe/
5986 https://www.mephistoslovenska.sk/mephisto-noah-ko%c5%been%c3%a9-panske-oxfordky-sk6550d-hnede-p-100.html
5987 https://www.stanleyphilippines.com/
5988 https://sign-in-att-100076.weeblysite.com/
5989 https://crystalkitchengranitecom.pages.dev/?9a7ee24f27dbe7f9eb705ab891fc5c88

In [49]:
#converting the list to dataframe
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection', 
                 'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record','Domain_Age', 
                 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 
                 'Label']

phishing = pd.DataFrame(phish_features, columns= feature_names)
phishing.head()

Domain  Have_IP  Have_At  URL_Length  \
0               doiw0zuhcw9rosjhic.pages.dev        0        0           0   
1                                    ipfs.io        0        0           1   
2                        cloudflare-ipfs.com        0        0           1   
3  start-a-complaint-meta-01061657.pages.dev        0        0           0   
4                       distritonorte.com.mx        0        0           0   

   URL_Depth  Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  \
0          1            0             0        0              0           0   
1          2            0             0        0              0           0   
2          2            0             0        0              1           0   
3          0            0             0        0              1           0   
4          3            0             0        0              0           0   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           1           1       0           0            0             0   
1          10           0       0           0            0             0   
2           6           0       0           0            0             0   
3           1           1       0           0            0             0   
4           5           0       0           0            0             0   

   Label  
0      1  
1      1  
2      1  
3      1  
4      1

Zebrane dane po przekonwertowaniu zapiszemy do pliku csv phishing.csv.

In [50]:
# Storing the extracted legitimate URLs fatures to csv file
phishing.to_csv('phishing.csv', index= False)

### 5. Ostateczny zbiór danych
W powyższej sekcji utworzyliśmy dwie ramki danych agregujące cechy stron prawdziwych i phishingowych. Teraz połączymy je w jedną ramkę danych i wyeksportujemy ją do pliku urldata.csv. Plik ten wykorzystamy na etapie machine learningu przeprowadzonego w osobnym notatniku.

In [51]:
#Concatenating the dataframes into one 
urldata = pd.concat([legitimate, phishing]).reset_index(drop=True)
urldata.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0          dewatergroep.be        0        0           0          0   
1             poppankki.fi        0        0           0          0   
2            ceskaposta.cz        0        0           0          0   
3  suncoastcreditunion.com        0        0           0          0   
4                   caf.fr        0        0           0          0   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Domain_Age  \
0            0             0        0              0           0          12   
1            0             0        0              0           0          14   
2            0             0        0              0           1           1   
3            0             0        0              0           0          21   
4            0             0        0              0           0          26   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           0       1           0            0             0      0  
1           0       0           0            0             0      0  
2           1       0           0            0             1      0  
3           0       0           0            0             0      0  
4           0       0           0            0             0      0

In [52]:
urldata.tail()

Domain  Have_IP  Have_At  URL_Length  \
11777                  www-iroblox.com        0        0           0   
11778                  iade-temmuz.sbs        0        0           0   
11779                   imtoken-bw.ist        0        0           0   
11780                     bet83008.com        0        0           0   
11781  kajhbscdquiwbjhd.weeblysite.com        0        0           0   

       URL_Depth  Redirection  https_Domain  TinyURL  Prefix/Suffix  \
11777          2            0             0        1              1   
11778          0            0             0        0              1   
11779          0            0             0        0              1   
11780          0            0             0        0              0   
11781          0            0             0        0              0   

       DNS_Record  Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  \
11777           0           0           1       0           0            0   
11778           0           0           1      -1          -1           -1   
11779           0           0           0       0           0            0   
11780           0           1           0       0           0            0   
11781           0          11           0       0           0            0   

       Web_Forwards  Label  
11777             0      1  
11778            -1      1  
11779             0      1  
11780             0      1  
11781             0      1

In [53]:
urldata.shape

(11782, 17)

Utworzony zbiór danych zapisujemy do pliku urldata.csv.

In [54]:
# Storing the data in CSV file
urldata.to_csv('urldata.csv', index=False)

### 6. Wniosek

Cel tego notebooka został osiągnięty. Wyodrębniliśmy 16 funkcji dla 11782 adresów URL, na które składa się 5999 adresów phishingowych i 5783 bezpiecznych adresów URL.

### 7. Źródła

```
https://archive.ics.uci.edu/ml/datasets/Phishing+Websites
https://pl.majestic.com/reports/majestic-million
https://pro.urlscan.io/search?additionalFilter=brand.key%3A*%3Bdate%3A%3Enow-24h%3Bpage.status%3A%22200%22&collapse=page.apexDomain
https://pro.urlscan.io/search?additionalFilter=brand.key%3A*&summary=true
https://openphish.com/
https://phishtank.org/
```
